"""
FuturSet Jobs Portal - Specialized Technical (B.Tech CSE/IT) & Multi-Selection Seeds
Covers:
1. Direct Merit & Walk-in Recruitments (GDS, Staff Nurses, CHO, Medical Officers, Primary Teachers)
2. Trade & Technical Apprenticeships (Western Railway RRC, Central Railway, IOCL, ONGC, DRDO, BEL)
3. Central Government IT (NIC Scientist-B, ISRO Scientist, DRDO Scientist, IBPS SO IT, SBI SCO, NIELIT, BISAG-N, CDAC, BARC, IB ACIO)
4. Gujarat State Government IT (GIL, GIPL, High Court Programmer, GPSC IT Director, SDC SOC, AMC/SMC IT)
5. PSU Technology Cadres (AAI IT, PowerGrid, BEL, ONGC, NTPC)
6. Premier Private & MNC Tech Recruiters (TCS NQT, Infosys SP/SE, Wipro Turbo, Jio Platforms, Adani Digital, GIFT City FinTech, Capgemini, LTTS)
"""
from datetime import datetime, timedelta
from typing import List, Dict, Any

def generate_all_tech_and_merit_jobs() -> List[Dict[str, Any]]:
    now = datetime.now()
    def future_date(days: int) -> str:
        return (now + timedelta(days=days)).strftime("%Y-%m-%d")

    def past_date(days: int) -> str:
        return (now - timedelta(days=days)).strftime("%Y-%m-%d")

    jobs: List[Dict[str, Any]] = [
        # =====================================================================
        # 1. DIRECT MERIT RECRUITMENTS (NO WRITTEN EXAM)
        # =====================================================================
        {
            "title": "Health & Family Welfare Dept Gujarat Staff Nurse Merit Recruitment 2026 (2,450 Posts)",
            "title_gu": "આરોગ્ય અને પરિવાર કલ્યાણ વિભાગ સ્ટાફ નર્સ વર્ગ-૩ સીધી મેરીટ ભરતી ૨૦૨૬ (૨,૪૫૦ જગ્યાઓ)",
            "organization": "Health & Family Welfare Department, Govt. of Gujarat",
            "department": "Commissioner of Health, Medical Services & Medical Education",
            "gov_level": "State",
            "state": "Gujarat",
            "district": "All Gujarat",
            "board_category": "Health",
            "vacancies": 2450,
            "qualification": "GNM Diploma or B.Sc. (Nursing) from a recognized University/Council with Gujarat Nursing Council Registration",
            "qualification_level": "Graduate",
            "age_min": 20,
            "age_max": 40,
            "age_relaxation_text": "SEBC/SC/ST: +5 yrs, Female Candidates: +5 yrs",
            "salary_text": "₹26,000/- Fix Pay for 5 Years -> 7th CPC Level-7 (₹39,900 - ₹1,26,600)",
            "start_date": past_date(12),
            "last_date": future_date(16),
            "exam_date": "No Written Exam (100% Direct Selection on GNM/B.Sc. Marks Merit List)",
            "notification_number": "COH/NURSE/2026/01",
            "notification_pdf_url": "https://ojas.gujarat.gov.in/AdvtDetailFiles/COH_2026_Nurse.pdf",
            "apply_url": "https://ojas.gujarat.gov.in",
            "official_website": "https://gujhealth.gujarat.gov.in",
            "application_fee": "General: ₹100. SC/ST/SEBC/EWS/Female: ₹0 (Exempted)",
            "selection_process": "100% Direct Merit based on Marks obtained in GNM / B.Sc Nursing degree -> Document Verification at Ahmedabad Civil Hospital.",
            "syllabus_summary": "No Exam Conducted. Selection calculated from academic aggregate percentage.",
            "source": "Gujarat Health Gazette",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "direct_merit",
            "job_category": "government",
            "is_btech_cse": 0,
            "experience_level": "fresher",
            "tech_stack": "",
            "ctc_lpa": 3.12
        },
        {
            "title": "National Health Mission (NHM Gujarat) Community Health Officer (CHO) 2026 (1,850 Posts)",
            "title_gu": "નેશનલ હેલ્થ મિશન (NHM ગુજરાત) કોમ્યુનિટી હેલ્થ ઓફિસર (CHO) મેરીટ આધારિત ભરતી ૨૦૨૬ (૧,૮૫૦ જગ્યાઓ)",
            "organization": "National Health Mission (NHM), Gujarat",
            "department": "State Health Society, Gandhinagar",
            "gov_level": "State",
            "state": "Gujarat",
            "district": "All Gujarat",
            "board_category": "Health",
            "vacancies": 1850,
            "qualification": "B.Sc Nursing / Post Basic B.Sc Nursing with integrated Certificate Program in Community Health (CPCH) or BAMS",
            "qualification_level": "Graduate",
            "age_min": 21,
            "age_max": 40,
            "age_relaxation_text": "As per NHM Gujarat guidelines",
            "salary_text": "Fixed Monthly Honorarium ₹25,000/- per month + Performance Incentive up to ₹10,000/- per month (Total ₹35,000/mo)",
            "start_date": past_date(8),
            "last_date": future_date(19),
            "exam_date": "Direct Merit Selection (Academic Marks & CPCH qualification verification)",
            "notification_number": "NHM/CHO/2026/03",
            "notification_pdf_url": "https://nhm.gujarat.gov.in/advt/CHO_Recruitment_2026.pdf",
            "apply_url": "https://arogyasathi.gujarat.gov.in",
            "official_website": "https://nhm.gujarat.gov.in",
            "application_fee": "All candidates: ₹0 (No application fee)",
            "selection_process": "Direct Merit Shortlisting on qualifying degree marks -> District Allocation -> Document Verification.",
            "syllabus_summary": "Direct Merit. Evaluation on aggregate medical/nursing scores.",
            "source": "NHM Gujarat Portal",
            "is_active": 1,
            "featured": 0,
            "selection_mode": "direct_merit",
            "job_category": "government",
            "is_btech_cse": 0,
            "experience_level": "fresher",
            "tech_stack": "",
            "ctc_lpa": 4.2
        },
        {
            "title": "WCD Gujarat Anganwadi Worker & Helper Direct Merit Bharti 2026 (10,400 Posts)",
            "title_gu": "મહિલા અને બાળ વિકાસ વિભાગ (WCD) આંગણવાડી કાર્યકર અને તેડાગર સીધી મેરીટ ભરતી ૨૦૨૬ (૧૦,૪૦૦ જગ્યાઓ)",
            "organization": "Women & Child Development Department, Govt. of Gujarat",
            "department": "Integrated Child Development Services (ICDS), Sachivalaya Gandhinagar",
            "gov_level": "State",
            "state": "Gujarat",
            "district": "All Gujarat",
            "board_category": "State",
            "vacancies": 10400,
            "qualification": "10th / 12th Pass (Higher Secondary) from Gujarat Secondary Board. Candidate must be local resident of respective ward/village.",
            "qualification_level": "10th/12th",
            "age_min": 18,
            "age_max": 33,
            "age_relaxation_text": "Local village resident criteria strictly applicable",
            "salary_text": "Fixed Monthly Honorarium: Anganwadi Worker ₹10,000/mo | Helper ₹5,500/mo",
            "start_date": past_date(15),
            "last_date": future_date(14),
            "exam_date": "No Exam (Computerized District-wise Merit List on 10th/12th percentages)",
            "notification_number": "WCD/ICDS/2026/04",
            "notification_pdf_url": "https://e-hrms.gujarat.gov.in/WCD_Notification_2026.pdf",
            "apply_url": "https://e-hrms.gujarat.gov.in",
            "official_website": "https://wcd.gujarat.gov.in",
            "application_fee": "Nil (₹0 for all women applicants)",
            "selection_process": "100% Automated System-generated Merit List based on class 10/12 board marks -> Ward level physical document check.",
            "syllabus_summary": "Direct Merit Calculation. No written test.",
            "source": "WCD Gujarat e-HRMS Portal",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "direct_merit",
            "job_category": "government",
            "is_btech_cse": 0,
            "experience_level": "fresher",
            "tech_stack": "",
            "ctc_lpa": 1.2
        },

        # =====================================================================
        # 2. TRADE & TECHNICAL APPRENTICESHIPS (DIRECT MERIT)
        # =====================================================================
        {
            "title": "Western Railway (RRC WR) Apprentice Recruitment 2026 (Ahmedabad, Vadodara, Rajkot - 3,624 Posts)",
            "title_gu": "વેસ્ટર્ન રેલ્વે (RRC WR) એપ્રેન્ટિસ ભરતી ૨૦૨૬ (અમદાવાદ, વડોદરા, રાજકોટ, ભાવનગર - ૩,૬૨૪ જગ્યાઓ)",
            "organization": "Railway Recruitment Cell, Western Railway (RRC WR)",
            "department": "Ministry of Railways, Govt. of India",
            "gov_level": "Central",
            "state": "Gujarat",
            "district": "All Gujarat",
            "board_category": "Apprenticeship",
            "vacancies": 3624,
            "qualification": "Matriculate / 10th Class pass with min 50% marks + ITI Certificate in relevant trade (NCVT/SCVT)",
            "qualification_level": "10th/12th",
            "age_min": 15,
            "age_max": 24,
            "age_relaxation_text": "SC/ST: +5 yrs, OBC: +3 yrs, PwD: +10 yrs",
            "salary_text": "Monthly Stipend ₹8,050/- to ₹10,500/- as per Apprentices Act 1961 + 20% quota in Railway Group D permanent posts",
            "start_date": past_date(10),
            "last_date": future_date(20),
            "exam_date": "No Exam / No Viva (Direct Selection on Average of 10th & ITI Marks)",
            "notification_number": "RRC/WR/02/2026/Apprentice",
            "notification_pdf_url": "https://www.rrc-wr.com/Notification/Apprentice_2026.pdf",
            "apply_url": "https://www.rrc-wr.com",
            "official_website": "https://wr.indianrailways.gov.in",
            "application_fee": "General/OBC Male: ₹100. SC/ST/PwD/Women: ₹0 (Nil)",
            "selection_process": "100% Direct Merit calculation (50% weightage to 10th percentage + 50% weightage to ITI trade certificate marks) -> Document Verification -> Medical fitness check.",
            "syllabus_summary": "No written test. Candidate merit determined strictly on academic scores.",
            "source": "RRC Western Railway Official Gazette",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "apprenticeship",
            "job_category": "government",
            "is_btech_cse": 0,
            "experience_level": "fresher",
            "tech_stack": "",
            "ctc_lpa": 1.2
        },
        {
            "title": "IOCL (Indian Oil) Gujarat Refinery Vadodara Trade & Technician Apprentice 2026 (470 Posts)",
            "title_gu": "ઇન્ડિયન ઓઇલ (IOCL) ગુજરાત રિફાઇનરી વડોદરા ટ્રેડ અને ટેકનિશિયન એપ્રેન્ટિસ ભરતી ૨૦૨૬ (૪૭૦ જગ્યાઓ)",
            "organization": "Indian Oil Corporation Limited (IOCL)",
            "department": "Refineries Division, Gujarat Refinery (Koyali, Vadodara)",
            "gov_level": "Central",
            "state": "Gujarat",
            "district": "વડોદરા",
            "board_category": "Apprenticeship",
            "vacancies": 470,
            "qualification": "3-Year Diploma in Chemical/Mechanical/Electrical/Instrumentation Engineering OR B.Sc. (Physics/Chemistry/Maths) OR ITI",
            "qualification_level": "Diploma",
            "age_min": 18,
            "age_max": 24,
            "age_relaxation_text": "SC/ST: +5 yrs, OBC (NCL): +3 yrs, PwD: +10 yrs",
            "salary_text": "Consolidated Monthly Stipend ₹10,500/- to ₹14,000/- per month + Subsidized Medical & Canteen facilities",
            "start_date": past_date(6),
            "last_date": future_date(22),
            "exam_date": "Direct Academic Shortlisting & Objective Assessment: December 2026 at Vadodara",
            "notification_number": "IOCL/GR/HR/APPR/2026",
            "notification_pdf_url": "https://www.iocl.com/download/Apprentice_Notification_Gujarat_2026.pdf",
            "apply_url": "https://www.iocl.com/apprenticeships",
            "official_website": "https://iocl.com",
            "application_fee": "All Categories: ₹0 (No fee)",
            "selection_process": "Merit list drawn based on percentage in qualifying Diploma / B.Sc / ITI followed by Pre-Engagement Medical Physical Examination.",
            "syllabus_summary": "Engineering Domain basics, Industrial Safety regulations, Chemical process basics, Reasoning & Arithmetic.",
            "source": "IOCL Official Portal",
            "is_active": 1,
            "featured": 0,
            "selection_mode": "apprenticeship",
            "job_category": "psu",
            "is_btech_cse": 0,
            "experience_level": "fresher",
            "tech_stack": "",
            "ctc_lpa": 1.5
        },
        {
            "title": "ONGC Gujarat (Ahmedabad, Mehsana, Ankleshwar) Graduate & Diploma Apprentice 2026 (680 Posts)",
            "title_gu": "ONGC ગુજરાત (અમદાવાદ, મહેસાણા, અંકલેશ્વર) ગ્રેજ્યુએટ અને ડિપ્લોમા એપ્રેન્ટિસ ભરતી ૨૦૨૬ (૬૮૦ જગ્યાઓ)",
            "organization": "Oil and Natural Gas Corporation (ONGC)",
            "department": "Western Onshore Basin, Gujarat Assets",
            "gov_level": "Central",
            "state": "Gujarat",
            "district": "All Gujarat",
            "board_category": "Apprenticeship",
            "vacancies": 680,
            "qualification": "B.E. / B.Tech / Diploma in CS, IT, Mechanical, Petroleum, Electrical or Graduate Degree (B.Com/B.Sc)",
            "qualification_level": "Engineering",
            "age_min": 18,
            "age_max": 24,
            "age_relaxation_text": "OBC: +3 yrs, SC/ST: +5 yrs",
            "salary_text": "Graduate Apprentice: ₹15,000/mo | Diploma Apprentice: ₹12,000/mo",
            "start_date": past_date(5),
            "last_date": future_date(25),
            "exam_date": "No Exam (Direct Merit Selection on NATS / NAPS Portal Scores)",
            "notification_number": "ONGC/APPR/GUJ/2026/01",
            "notification_pdf_url": "https://ongcindia.com/documents/apprentice_guj_2026.pdf",
            "apply_url": "https://ongcapprentices.ongc.co.in",
            "official_website": "https://ongcindia.com",
            "application_fee": "₹0 (Exempted for all)",
            "selection_process": "Direct Merit drawn from NATS/NAPS portal percentage score.",
            "syllabus_summary": "Direct Merit. No written examination.",
            "source": "ONGC Official Careers",
            "is_active": 1,
            "featured": 0,
            "selection_mode": "apprenticeship",
            "job_category": "psu",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "Basic Computer Skills, Engineering Fundamentals",
            "ctc_lpa": 1.8
        },

        # =====================================================================
        # 3. WALK-IN INTERVIEWS & DIRECT SCREENINGS
        # =====================================================================
        {
            "title": "Gujarat Health Dept Ad-hoc Medical Officers (MBBS Class-2) Walk-in Drive 2026 (650 Posts)",
            "title_gu": "આરોગ્ય વિભાગ મેડિકલ ઓફિસર વર્ગ-૨ સીધો વોક-ઇન ઇન્ટરવ્યુ ૨૦૨૬ (૬૫૦ જગ્યાઓ - સિવિલ હોસ્પિટલ)",
            "organization": "Commissionerate of Health, Medical Services & Medical Education, Gujarat",
            "department": "Health & Family Welfare Department, Gandhinagar",
            "gov_level": "State",
            "state": "Gujarat",
            "district": "All Gujarat",
            "board_category": "Health",
            "vacancies": 650,
            "qualification": "MBBS degree from an NMC recognized medical college with Gujarat Medical Council (GMC) registration",
            "qualification_level": "Graduate",
            "age_min": 21,
            "age_max": 40,
            "age_relaxation_text": "Reserved categories: +5 yrs relaxation",
            "salary_text": "Monthly Consolidated Fix Pay ₹60,000/- to ₹75,000/- (Level 10 equivalent)",
            "start_date": past_date(4),
            "last_date": future_date(10),
            "exam_date": "Weekly Walk-in Interview: Every Tuesday & Friday at Block-5, Sachivalaya, Gandhinagar",
            "notification_number": "COH/MO/WALKIN/2026",
            "notification_pdf_url": "https://gujhealth.gujarat.gov.in/walkin_mo_2026.pdf",
            "apply_url": "https://gujhealth.gujarat.gov.in",
            "official_website": "https://gujhealth.gujarat.gov.in",
            "application_fee": "₹0 (Nil)",
            "selection_process": "Same-day Walk-in Interview + Original Document Verification -> On-the-spot Appointment Letter issued.",
            "syllabus_summary": "Clinical medicine, Obstetrics & Gynaecology, Surgery, Community Health and National Health Programmes.",
            "source": "Health Dept Gujarat Notice",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "walk_in",
            "job_category": "government",
            "is_btech_cse": 0,
            "experience_level": "fresher",
            "tech_stack": "",
            "ctc_lpa": 9.0
        },
        {
            "title": "Gujarat Technical Education Guest Lecturers & Ad-hoc Assistant Professors Walk-in 2026 (820 Posts)",
            "title_gu": "તકનીકી શિક્ષણ નિયામક કચેરી (DTE) સરકારી એન્જિનિયરિંગ કોલેજો મુલાકાતી અધ્યાપક વોક-ઇન ભરતી ૨૦૨૬ (૮૨૦ જગ્યાઓ)",
            "organization": "Directorate of Technical Education (DTE), Gujarat",
            "department": "Education Department, Govt. of Gujarat",
            "gov_level": "State",
            "state": "Gujarat",
            "district": "All Gujarat",
            "board_category": "Teaching",
            "vacancies": 820,
            "qualification": "B.E. / B.Tech / M.E. / M.Tech in CSE, IT, Civil, Mechanical, Electrical with First Class",
            "qualification_level": "Engineering",
            "age_min": 21,
            "age_max": 45,
            "age_relaxation_text": "As per AICTE and Gujarat Govt norms",
            "salary_text": "₹1,500/- per lecture (Maximum ₹45,000/- per month honorarium)",
            "start_date": past_date(7),
            "last_date": future_date(15),
            "exam_date": "Walk-in Interview scheduled at Government Engineering Colleges (Ahmedabad, Surat, Rajkot, Bhavnagar)",
            "notification_number": "DTE/GUEST/2026/02",
            "notification_pdf_url": "https://dte.gujarat.gov.in/notifications/Guest_Lecturer_2026.pdf",
            "apply_url": "https://dte.gujarat.gov.in",
            "official_website": "https://dte.gujarat.gov.in",
            "application_fee": "₹0 (Nil)",
            "selection_process": "Walk-in Technical Viva & Teaching Demonstration (15 minutes micro-teaching) -> Panel Merit list.",
            "syllabus_summary": "Subject Domain concepts (Data Structures, Algorithms, DBMS, Operating Systems, Networks).",
            "source": "DTE Gujarat Official Portal",
            "is_active": 1,
            "featured": 0,
            "selection_mode": "walk_in",
            "job_category": "government",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "DSA, OS, DBMS, Python, Java",
            "ctc_lpa": 5.4
        },

        # =====================================================================
        # 4. B.TECH CSE / IT JOBS - CENTRAL GOVERNMENT IT & RESEARCH
        # =====================================================================
        {
            "title": "National Informatics Centre (NIC) Scientist-B (Computer Science & IT) 2026 (340 Posts)",
            "title_gu": "નેશનલ ઇન્ફોર્મેટિક્સ સેન્ટર (NIC) સાયન્ટિસ્ટ-બી (કમ્પ્યુટર સાયન્સ & IT) ભરતી ૨૦૨૬ (૩૪૦ જગ્યાઓ - લેવલ ૧૦)",
            "organization": "National Informatics Centre (NIC) / NIELIT",
            "department": "Ministry of Electronics & Information Technology (MeitY), Govt. of India",
            "gov_level": "Central",
            "state": "All India",
            "district": "All India",
            "board_category": "Central",
            "vacancies": 340,
            "qualification": "B.E. / B.Tech in Computer Science / Computer Engineering / Information Technology / Software Engineering or MCA",
            "qualification_level": "Engineering",
            "age_min": 21,
            "age_max": 30,
            "age_relaxation_text": "OBC: +3 yrs, SC/ST: +5 yrs, PwD: +10 yrs",
            "salary_text": "7th CPC Pay Matrix Level-10 (₹56,100 - ₹1,77,500) + DA, HRA (Gross ~₹1,05,000/mo, CTC ₹15.5 LPA)",
            "start_date": past_date(18),
            "last_date": future_date(14),
            "exam_date": "Online Computer Based Examination: December 2026 across All Major Cities including Ahmedabad",
            "notification_number": "NIELIT/NIC/2026/01",
            "notification_pdf_url": "https://www.calicut.nielit.in/nic26/PDF/Detailed_Advt_Scientist_B.pdf",
            "apply_url": "https://www.calicut.nielit.in/nic26",
            "official_website": "https://www.nic.in",
            "application_fee": "General/OBC/EWS: ₹800. SC/ST/Women/PwD: ₹0 (Exempted)",
            "selection_process": "Online Objective Written Test (120 Marks: 65% CS Technical + 35% Generic Aptitude) -> Technical Interview (Weightage 85:15).",
            "syllabus_summary": "Data Structures, Algorithms, Computer Networks, DBMS, Operating Systems, Compiler Design, Cyber Security, Software Engineering, Object-Oriented Programming (Java/Python).",
            "source": "MeitY Employment Gazette",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "written_exam",
            "job_category": "government",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "Algorithms, Linux, C++, Java, Python, SQL, Networks, Cyber Security",
            "ctc_lpa": 15.5
        },
        {
            "title": "ISRO Scientist/Engineer 'SC' (Computer Science) Recruitment 2026 (65 Posts)",
            "title_gu": "ઇસરો (ISRO) સાયન્ટિસ્ટ/ઈજનેર 'SC' (કમ્પ્યુટર સાયન્સ) ભરતી ૨૦૨૬ (૬૫ જગ્યાઓ - ICRB પરીક્ષા)",
            "organization": "Indian Space Research Organisation (ISRO)",
            "department": "Department of Space, Govt. of India (SAC Ahmedabad, URSC, VSSC)",
            "gov_level": "Central",
            "state": "All India",
            "district": "All India",
            "board_category": "Scientific",
            "vacancies": 65,
            "qualification": "B.E. / B.Tech in Computer Science & Engineering with aggregate min 65% marks or 6.84 CGPA",
            "qualification_level": "Engineering",
            "age_min": 21,
            "age_max": 28,
            "age_relaxation_text": "OBC: +3 yrs, SC/ST: +5 yrs as per Govt of India norms",
            "salary_text": "7th CPC Pay Matrix Level-10 (₹56,100 - ₹1,77,500) + Free Housing / HRA, Transport & Medical (CTC ₹16.0 LPA)",
            "start_date": past_date(10),
            "last_date": future_date(15),
            "exam_date": "ISRO ICRB Centralized Written Test: January 2027",
            "notification_number": "ISRO:ICRB:03(CS):2026",
            "notification_pdf_url": "https://www.isro.gov.in/media_isro/pdf/recruitment/ADV_CS_2026.pdf",
            "apply_url": "https://www.isro.gov.in/Careers.html",
            "official_website": "https://www.isro.gov.in",
            "application_fee": "₹250 processing fee (Refundable ₹150 upon appearing for exam). Women/SC/ST: Exempted",
            "selection_process": "Part A: Written Test (80 MCQ CS Discipline) + Part B: Aptitude (20 MCQ) -> Technical Interview (Weightage 50:50).",
            "syllabus_summary": "Computer Architecture, High Performance Computing, OS, Algorithms, Cloud Systems, Satellite Image Processing, Cryptography.",
            "source": "ISRO ICRB Portal",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "written_exam",
            "job_category": "government",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "C/C++, Python, CUDA, Distributed Systems, Linux, RTOS",
            "ctc_lpa": 16.0
        },
        {
            "title": "DRDO Scientist 'B' (Computer Science & Engineering) Recruitment 2026 (85 Posts)",
            "title_gu": "ડીઆરડીઓ (DRDO) સાયન્ટિસ્ટ 'બી' (કમ્પ્યુટર એન્જિનિયરિંગ) ભરતી ૨૦૨૬ (RAC પોર્ટલ - ૮૫ જગ્યાઓ)",
            "organization": "Defence Research & Development Organisation (DRDO)",
            "department": "Recruitment & Assessment Centre (RAC), Ministry of Defence",
            "gov_level": "Central",
            "state": "All India",
            "district": "All India",
            "board_category": "Defence",
            "vacancies": 85,
            "qualification": "First Class Bachelor's Degree in Computer Science & Engineering + Valid GATE 2024 / 2025 / 2026 Score in CS",
            "qualification_level": "Engineering",
            "age_min": 21,
            "age_max": 28,
            "age_relaxation_text": "OBC: +3 yrs, SC/ST: +5 yrs, Central Govt civilian employees: +5 yrs",
            "salary_text": "7th CPC Level-10 (₹56,100 - ₹1,77,500) + DA + Professional Update Allowance + Medical (CTC ₹16.2 LPA)",
            "start_date": past_date(14),
            "last_date": future_date(18),
            "exam_date": "Personal Interview at RAC DRDO Complex, Delhi: November 2026",
            "notification_number": "DRDO/RAC/Advt_148/CS",
            "notification_pdf_url": "https://rac.gov.in/download/advt_148_scientist_b_cs.pdf",
            "apply_url": "https://rac.gov.in",
            "official_website": "https://drdo.gov.in",
            "application_fee": "General/OBC/EWS Male: ₹100. SC/ST/PwD & Women: ₹0",
            "selection_process": "Shortlisting on GATE CS Score (1:10 ratio) -> Personal Technical Interview (80% GATE Score + 20% Interview).",
            "syllabus_summary": "GATE CS Syllabus: Algorithms, Complexity Theory, System Programming, Secure Coding, AI & Neural Networks.",
            "source": "DRDO RAC Gazette",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "written_exam",
            "job_category": "government",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "C, C++, Assembly, Python, Cryptography, Deep Learning, Linux Kernel",
            "ctc_lpa": 16.2
        },
        {
            "title": "IBPS Specialist Officer (IT Officer Scale-I) Common Recruitment 2026 (450 Posts)",
            "title_gu": "IBPS સ્પેશિયાલિસ્ટ ઓફિસર (IT ઓફિસર સ્કેલ-૧) સરકારી બેંકોમાં ભરતી ૨૦૨૬ (૪૫૦ જગ્યાઓ)",
            "organization": "Institute of Banking Personnel Selection (IBPS)",
            "department": "Participating Public Sector Banks (Bank of Baroda, PNB, Canara Bank, Union Bank)",
            "gov_level": "Central",
            "state": "All India",
            "district": "All India",
            "board_category": "Banking",
            "vacancies": 450,
            "qualification": "4-year Engineering Degree (B.Tech / B.E.) in Computer Science / Computer Applications / Information Technology or MCA",
            "qualification_level": "Engineering",
            "age_min": 20,
            "age_max": 30,
            "age_relaxation_text": "OBC: +3 yrs, SC/ST: +5 yrs, PwD: +10 yrs",
            "salary_text": "Pay Scale ₹48,480 - ₹85,920 (Scale-I Officer) + DA, Special Allowance, Leased Accommodation (CTC ₹11.5 LPA)",
            "start_date": past_date(8),
            "last_date": future_date(12),
            "exam_date": "Prelims Exam: December 2026 | Mains Exam (IT Professional Knowledge): January 2027",
            "notification_number": "IBPS/CRP-SPL-XIV/2026",
            "notification_pdf_url": "https://www.ibps.in/wp-content/uploads/Advt_CRP_SPL_XIV.pdf",
            "apply_url": "https://ibps.in",
            "official_website": "https://ibps.in",
            "application_fee": "General/OBC/EWS: ₹850. SC/ST/PwD: ₹175",
            "selection_process": "Online Prelims (Reasoning, English, Quant) -> Online Mains (60 Questions IT Professional Knowledge) -> Common Interview.",
            "syllabus_summary": "Database Management (RDBMS, Normalization, SQL), Computer Networks & Security, Software Engineering Models, Data Structures, Web Technologies.",
            "source": "IBPS Official CRP Portal",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "written_exam",
            "job_category": "government",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "SQL, Oracle, Computer Networks, Linux, Java, Cyber Security, FinTech",
            "ctc_lpa": 11.5
        },
        {
            "title": "SBI Specialist Cadre Officer (System Analyst & Cloud Administrator) 2026 (220 Posts)",
            "title_gu": "સ્ટેટ બેંક ઓફ ઇન્ડિયા (SBI) સ્પેશિયાલિસ્ટ કેડર ઓફિસર (સિસ્ટમ એનાલિસ્ટ / ક્લાઉડ એડમિન) ભરતી ૨૦૨૬ (૨૨૦ જગ્યાઓ)",
            "organization": "State Bank of India (SBI)",
            "department": "Global IT Centre (GITC), Belapur & Ahmedabad Local Head Office",
            "gov_level": "Central",
            "state": "All India",
            "district": "All India",
            "board_category": "Banking",
            "vacancies": 220,
            "qualification": "B.E. / B.Tech in Computer Science / Computer Science & Engineering / Information Technology / Software Engineering",
            "qualification_level": "Engineering",
            "age_min": 23,
            "age_max": 35,
            "age_relaxation_text": "OBC: +3 yrs, SC/ST: +5 yrs",
            "salary_text": "MMGS-II Pay Scale (₹64,820 - ₹93,960) + Bank Quarters / Perks (Total CTC ₹17.5 LPA to ₹22 LPA)",
            "start_date": past_date(11),
            "last_date": future_date(17),
            "exam_date": "Shortlisting on profile & Technical Virtual Interview: December 2026",
            "notification_number": "CRPD/SCO/2026-27/15",
            "notification_pdf_url": "https://sbi.co.in/documents/careers/SCO_IT_2026_Advt.pdf",
            "apply_url": "https://bank.sbi/careers",
            "official_website": "https://sbi.co.in",
            "application_fee": "General/EWS/OBC: ₹750. SC/ST/PwD: Nil (₹0)",
            "selection_process": "Shortlisting by Qualification & Technical Background -> Technical Interview (100 Marks) -> Merit List.",
            "syllabus_summary": "Cloud Architecture (AWS/Azure), Docker, Kubernetes, CI/CD pipelines, Microservices, RDBMS & Enterprise Security.",
            "source": "SBI Official Careers Portal",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "walk_in",
            "job_category": "government",
            "is_btech_cse": 1,
            "experience_level": "experienced",
            "tech_stack": "AWS, Azure, Docker, Kubernetes, Python, Linux, Microservices, CI/CD",
            "ctc_lpa": 18.5
        },
        {
            "title": "BISAG-N Gandhinagar Scientist & Software Engineer Recruitment 2026 (45 Posts)",
            "title_gu": "બિઝાગ-એન ગાંધીનગર (BISAG-N) સાયન્ટિફિક ઓફિસર અને સોફ્ટવેર એન્જિનિયર ભરતી ૨૦૨૬ (૪૫ જગ્યાઓ)",
            "organization": "Bhaskaracharya National Institute for Space Applications and Geo-informatics (BISAG-N)",
            "department": "Ministry of Electronics & Information Technology, Gandhinagar Campus, Gujarat",
            "gov_level": "Central",
            "state": "Gujarat",
            "district": "ગાંધીનગર",
            "board_category": "Scientific",
            "vacancies": 45,
            "qualification": "B.E. / B.Tech in Computer Science / Information Technology / Software Engineering with min 60% marks",
            "qualification_level": "Engineering",
            "age_min": 21,
            "age_max": 32,
            "age_relaxation_text": "Government of India norms applicable",
            "salary_text": "Consolidated Pay ₹50,000/- to ₹85,000/- per month based on experience and role",
            "start_date": past_date(9),
            "last_date": future_date(21),
            "exam_date": "Technical Coding Round & Interview at BISAG-N Campus, Infocity Gandhinagar: December 2026",
            "notification_number": "BISAG-N/SE/2026/01",
            "notification_pdf_url": "https://bisag-n.gov.in/careers/SE_Advt_2026.pdf",
            "apply_url": "https://bisag-n.gov.in",
            "official_website": "https://bisag-n.gov.in",
            "application_fee": "Nil (₹0 for all candidates)",
            "selection_process": "Technical Evaluation & Hands-on Coding Task -> Personal Technical Interview.",
            "syllabus_summary": "Web GIS applications, Spatial Databases, Python (GeoPandas, GDAL), Django, React, RESTful APIs, Open Source GIS (QGIS, PostGIS).",
            "source": "BISAG-N Official Gazette",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "coding_test",
            "job_category": "government",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "Python, Django, PostgreSQL, PostGIS, React, GIS, REST APIs",
            "ctc_lpa": 8.5
        },
        {
            "title": "C-DAC Project Engineer (Full Stack, Cloud & AI/ML) Recruitment 2026 (180 Posts)",
            "title_gu": "સી-ડેક (C-DAC) પ્રોજેક્ટ એન્જિનિયર (AI/ML, ક્લાઉડ અને સુપરકમ્પ્યુટિંગ) ભરતી ૨૦૨૬ (૧૮૦ જગ્યાઓ)",
            "organization": "Centre for Development of Advanced Computing (C-DAC)",
            "department": "National Supercomputing Mission (NSM), MeitY, Govt. of India",
            "gov_level": "Central",
            "state": "All India",
            "district": "All India",
            "board_category": "Central",
            "vacancies": 180,
            "qualification": "B.E. / B.Tech in Computer Science / Information Technology / Electronics or MCA with min 65% marks",
            "qualification_level": "Engineering",
            "age_min": 21,
            "age_max": 35,
            "age_relaxation_text": "OBC: +3 yrs, SC/ST: +5 yrs, PwD: +10 yrs",
            "salary_text": "CTC ₹6.0 LPA to ₹10.5 LPA (₹44,900 - ₹75,000/mo) depending on post qualifications",
            "start_date": past_date(13),
            "last_date": future_date(11),
            "exam_date": "Online Technical Test & Coding Interview: December 2026",
            "notification_number": "CDAC/CORP/PE/2026/02",
            "notification_pdf_url": "https://www.cdac.in/index.aspx?id=advt_PE_2026.pdf",
            "apply_url": "https://www.cdac.in/careers",
            "official_website": "https://www.cdac.in",
            "application_fee": "General/OBC: ₹500. SC/ST/PwD/Women: ₹0",
            "selection_process": "Online Written Screening Test -> Hands-on Coding Assessment -> Technical Interview.",
            "syllabus_summary": "Object-Oriented Programming (Java/C++), Data Structures, Cloud Computing, Linux System Administration, PyTorch/TensorFlow.",
            "source": "C-DAC Official Portal",
            "is_active": 1,
            "featured": 0,
            "selection_mode": "coding_test",
            "job_category": "government",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "Java, Python, C++, Linux, Docker, PyTorch, Cloud, SQL",
            "ctc_lpa": 9.5
        },

        # =====================================================================
        # 5. B.TECH CSE / IT JOBS - GUJARAT STATE GOVERNMENT IT ROLES
        # =====================================================================
        {
            "title": "Gujarat Informatics Limited (GIL) Senior Software Developer & Project Manager 2026 (35 Posts)",
            "title_gu": "ગુજરાત ઇન્ફોર્મેટિક્સ લિમિટેડ (GIL) સિનિયર સોફ્ટવેર ડેવલપર & ડેટાબેઝ એડમિન ભરતી ૨૦૨૬ (૩૫ જગ્યાઓ - સચિવાલય)",
            "organization": "Gujarat Informatics Limited (GIL)",
            "department": "Department of Science & Technology (DST), Govt. of Gujarat, Gandhinagar",
            "gov_level": "State",
            "state": "Gujarat",
            "district": "ગાંધીનગર",
            "board_category": "State",
            "vacancies": 35,
            "qualification": "B.E. / B.Tech in Computer Engineering / Information Technology or MCA from a recognized University",
            "qualification_level": "Engineering",
            "age_min": 21,
            "age_max": 38,
            "age_relaxation_text": "Gujarat State domicile reservation rules apply",
            "salary_text": "Fix Pay ₹45,000/- to ₹85,000/- per month + Performance Allowance (Annual CTC ₹6.5 to ₹11.5 LPA)",
            "start_date": past_date(12),
            "last_date": future_date(16),
            "exam_date": "Technical Written Test & Live Coding Interview: December 2026 at Gandhinagar",
            "notification_number": "GIL/DST/RECT/2026/01",
            "notification_pdf_url": "https://gil.gujarat.gov.in/sites/default/files/recruitment_2026_dev.pdf",
            "apply_url": "https://gil.gujarat.gov.in/careers",
            "official_website": "https://gil.gujarat.gov.in",
            "application_fee": "General: ₹200. Reserved Categories: ₹100",
            "selection_process": "Stage 1: Technical MCQ & Coding Exam (100 Marks) -> Stage 2: Personal Technical Interview (50 Marks).",
            "syllabus_summary": "Full Stack Web Development (PHP/Python/Node.js), MySQL/PostgreSQL, Vue.js/React, REST API architecture, Git, E-Governance security guidelines.",
            "source": "GIL Official Notice",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "coding_test",
            "job_category": "government",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "PHP, Python, Node.js, PostgreSQL, React, Angular, Linux, REST API",
            "ctc_lpa": 8.0
        },
        {
            "title": "Gujarat High Court Computer Programmer & IT System Officer 2026 (48 Posts)",
            "title_gu": "ગુજરાત હાઇકોર્ટ કમ્પ્યુટર પ્રોગ્રામર અને IT સિસ્ટમ ઓફિસર સીધી ભરતી ૨૦૨૬ (૪૮ જગ્યાઓ - સોલા અમદાવાદ)",
            "organization": "High Court of Gujarat (Sola, Ahmedabad)",
            "department": "Information Technology Department, High Court Registry",
            "gov_level": "State",
            "state": "Gujarat",
            "district": "અમદાવાદ",
            "board_category": "High Court",
            "vacancies": 48,
            "qualification": "B.E. / B.Tech in Computer Science / Information Technology or MCA with min 55% marks from recognized University",
            "qualification_level": "Engineering",
            "age_min": 18,
            "age_max": 35,
            "age_relaxation_text": "SEBC/SC/ST: +5 yrs, Women candidates: +5 yrs",
            "salary_text": "7th CPC Pay Matrix Level-8 (₹44,900 - ₹1,42,400) + High Court Special Allowance (Gross ~₹72,000/mo)",
            "start_date": past_date(9),
            "last_date": future_date(15),
            "exam_date": "Elimination MCQ Test: November 2026 | Practical Programming & Viva: January 2027",
            "notification_number": "HCG/IT/2026/02",
            "notification_pdf_url": "https://gujarathighcourt.nic.in/currentopenings/IT_Officer_2026.pdf",
            "apply_url": "https://hc-ojas.gujarat.gov.in",
            "official_website": "https://gujarathighcourt.nic.in",
            "application_fee": "General: ₹700. SC/ST/SEBC/EWS/Ex-SM: ₹350",
            "selection_process": "1. Elimination Objective Test (100 Marks) -> 2. Computer Practical Programming Test (100 Marks in Java/PHP/SQL) -> 3. Viva-voce (20 Marks).",
            "syllabus_summary": "Core Java, Python, PHP, Relational Databases (PostgreSQL, Oracle), Linux Server administration, Network security, Legal Informatics.",
            "source": "Gujarat High Court Gazette",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "written_exam",
            "job_category": "government",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "Java, PHP, SQL, Linux Administration, Network Security, PostgreSQL",
            "ctc_lpa": 10.2
        },
        {
            "title": "GPSC Assistant Director (Information Technology) Class-1 Recruitment 2026 (18 Posts)",
            "title_gu": "GPSC મદદનીશ નિયામક (માહિતી ટેકનોલોજી) વર્ગ-૧ સીધી ભરતી ૨૦૨૬ (૧૮ જગ્યાઓ - વિજ્ઞાન અને પ્રૌદ્યોગિકી વિભાગ)",
            "organization": "Gujarat Public Service Commission (GPSC)",
            "department": "Science & Technology Department, Sachivalaya, Gandhinagar",
            "gov_level": "State",
            "state": "Gujarat",
            "district": "ગાંધીનગર",
            "board_category": "GPSC",
            "vacancies": 18,
            "qualification": "Bachelor's Degree in Engineering / Technology in Computer Engineering / IT or Master's Degree in Computer Application (MCA)",
            "qualification_level": "Engineering",
            "age_min": 21,
            "age_max": 40,
            "age_relaxation_text": "Reserved categories & Gujarat Women: +5 yrs",
            "salary_text": "7th Pay Commission Level-10 (₹56,100 - ₹1,77,500) Class-1 Gazetted Officer",
            "start_date": past_date(14),
            "last_date": future_date(10),
            "exam_date": "Preliminary Primary Test: December 2026 | Interview: March 2027",
            "notification_number": "GPSC/202627/22",
            "notification_pdf_url": "https://gpsc.gujarat.gov.in/Documents/Advertisment_Files/GPSC_IT_Class1_2026.pdf",
            "apply_url": "https://gpsc-ojas.gujarat.gov.in",
            "official_website": "https://gpsc.gujarat.gov.in",
            "application_fee": "General: ₹100. Reserved Categories & Women of Gujarat: ₹0 (Exempted)",
            "selection_process": "Preliminary Primary Test (300 Marks: 100 General Studies + 200 CS/IT Technical) -> Personality Test (Interview 100 Marks).",
            "syllabus_summary": "Part A: General Studies (100 Marks). Part B: Software Engineering, Cloud Architecture, Big Data, Cyber Law, IT Act 2000, AI Ethics (200 Marks).",
            "source": "GPSC OJAS Portal",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "written_exam",
            "job_category": "government",
            "is_btech_cse": 1,
            "experience_level": "experienced",
            "tech_stack": "E-Governance, Cyber Security, Cloud Architecture, IT Policy, DBMS",
            "ctc_lpa": 14.5
        },
        {
            "title": "Gujarat State Data Center (SDC Gandhinagar) SOC Analyst & Cyber Security Engineer 2026 (20 Posts)",
            "title_gu": "ગુજરાત સ્ટેટ ડેટા સેન્ટર (SDC ગાંધીનગર) સાયબર સિક્યુરિટી એન્જિનિયર અને SOC એનાલિસ્ટ ભરતી ૨૦૨૬ (૨૦ જગ્યાઓ)",
            "organization": "Gujarat State Data Center (SDC) / DST Gujarat",
            "department": "Department of Science & Technology, Infocity, Gandhinagar",
            "gov_level": "State",
            "state": "Gujarat",
            "district": "ગાંધીનગર",
            "board_category": "State",
            "vacancies": 20,
            "qualification": "B.E. / B.Tech in CSE / IT / Cyber Security with CEH / CompTIA Security+ / CCNA preferred",
            "qualification_level": "Engineering",
            "age_min": 21,
            "age_max": 35,
            "age_relaxation_text": "Standard state norms apply",
            "salary_text": "Fix Monthly Pay ₹55,000/- to ₹1,10,000/- per month based on certification and experience (CTC ₹8 to ₹14 LPA)",
            "start_date": past_date(6),
            "last_date": future_date(23),
            "exam_date": "Hands-on Technical Assessment & Interview at SDC Gandhinagar: December 2026",
            "notification_number": "SDC/CYBER/2026/03",
            "notification_pdf_url": "https://dst.gujarat.gov.in/sdc/cyber_engineer_2026.pdf",
            "apply_url": "https://dst.gujarat.gov.in",
            "official_website": "https://dst.gujarat.gov.in",
            "application_fee": "₹0 (No application fee)",
            "selection_process": "Shortlisting -> Hands-on Lab Test (Packet analysis, SIEM logs, Incident Response) -> Technical Interview.",
            "syllabus_summary": "Network Protocols, Firewall configuration, SIEM (Splunk/ELK), Vulnerability Assessment (Nessus), ISO 27001 standards.",
            "source": "DST Gujarat Official Notice",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "coding_test",
            "job_category": "government",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "SIEM, Splunk, Linux, Wireshark, Firewalls, Python, CEH, Incident Response",
            "ctc_lpa": 10.5
        },

        # =====================================================================
        # 6. B.TECH CSE / IT JOBS - PSU TECHNOLOGY CADRES
        # =====================================================================
        {
            "title": "Airports Authority of India (AAI) Junior Executive (Information Technology) 2026 (120 Posts)",
            "title_gu": "એરપોર્ટ ઓથોરિટી ઓફ ઇન્ડિયા (AAI) જુનિયર એક્ઝિક્યુટિવ (ઇન્ફોર્મેશન ટેકનોલોજી) ભરતી ૨૦૨૬ (૧૨૦ જગ્યાઓ - CTC ₹૧૩ લાખ)",
            "organization": "Airports Authority of India (AAI)",
            "department": "Information Technology Directorate, Rajiv Gandhi Bhawan, New Delhi",
            "gov_level": "Central",
            "state": "All India",
            "district": "All India",
            "board_category": "Aviation",
            "vacancies": 120,
            "qualification": "Full time regular B.E. / B.Tech Degree in Computer Science / Computer Engineering / IT with min 60% marks",
            "qualification_level": "Engineering",
            "age_min": 18,
            "age_max": 27,
            "age_relaxation_text": "OBC: +3 yrs, SC/ST: +5 yrs, PwD: +10 yrs",
            "salary_text": "Executive E-1 Scale (₹40,000 - 3% - ₹1,40,000) + DA 43.8% + Perks 35% + HRA (Total CTC ~₹13.2 LPA)",
            "start_date": past_date(11),
            "last_date": future_date(19),
            "exam_date": "Online Computer Based Test (CBT): December 2026 (No GATE Score Required)",
            "notification_number": "AAI/DR/IT/04/2026",
            "notification_pdf_url": "https://www.aai.aero/sites/default/files/recruitment/Advt_JE_IT_2026.pdf",
            "apply_url": "https://www.aai.aero/en/careers/recruitment",
            "official_website": "https://www.aai.aero",
            "application_fee": "General/OBC/EWS: ₹1000. SC/ST/Female/PwD: ₹0 (Exempted)",
            "selection_process": "Computer Based Online Examination (120 Marks: 70% CS Technical + 30% Aptitude) -> Document Verification. (NO INTERVIEW).",
            "syllabus_summary": "Computer Networks, Database Systems, Operating Systems, Software Engineering, Web Technologies, Cyber Security, General Intelligence & Reasoning.",
            "source": "AAI Careers Gazette",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "written_exam",
            "job_category": "psu",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "Networking, SQL, Linux, Cloud Infrastructure, Cyber Security",
            "ctc_lpa": 13.2
        },
        {
            "title": "PowerGrid (PGCIL) Engineer Trainee (Computer Science) Recruitment 2026 (95 Posts)",
            "title_gu": "પાવરગ્રીડ (PGCIL) એન્જિનિયર તાલીમાર્થી (કમ્પ્યુટર સાયન્સ) ભરતી ૨૦૨૬ (૯૫ જગ્યાઓ - CTC ₹૧૫ લાખ)",
            "organization": "Power Grid Corporation of India Limited (PowerGrid)",
            "department": "IT & Telecom Directorate, Western Region (Vadodara)",
            "gov_level": "Central",
            "state": "All India",
            "district": "All India",
            "board_category": "PSU",
            "vacancies": 95,
            "qualification": "Full time B.E. / B.Tech / B.Sc (Engg.) in Computer Science / Computer Engineering / IT with min 65% marks",
            "qualification_level": "Engineering",
            "age_min": 18,
            "age_max": 28,
            "age_relaxation_text": "OBC: +3 yrs, SC/ST: +5 yrs",
            "salary_text": "Pay Scale ₹40,000 - ₹1,40,000 (E-1 Trainee) -> On confirmation ₹50,000 - ₹1,60,000 (E-2) (CTC ₹15.0 LPA)",
            "start_date": past_date(13),
            "last_date": future_date(15),
            "exam_date": "Online Written CBT: December 2026 across India",
            "notification_number": "CC/08/2026/ET_CS",
            "notification_pdf_url": "https://www.powergrid.in/sites/default/files/Advt_ET_CS_2026.pdf",
            "apply_url": "https://www.powergrid.in/online-application",
            "official_website": "https://www.powergrid.in",
            "application_fee": "General/OBC/EWS: ₹500. SC/ST/PwD/Ex-SM: ₹0",
            "selection_process": "Computer Based Test (Part-1 120 Technical CS questions + Part-2 50 General Aptitude) -> Group Discussion & Personal Interview.",
            "syllabus_summary": "Data Structures, Algorithms, Computer Networks, Operating Systems, Database Management, Cloud Computing, SCADA IT.",
            "source": "PowerGrid Career Portal",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "written_exam",
            "job_category": "psu",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "Algorithms, Computer Networks, Linux, DBMS, Python, Enterprise IT",
            "ctc_lpa": 15.0
        },
        {
            "title": "Bharat Electronics Limited (BEL) Software Engineer (SDE) Recruitment 2026 (110 Posts)",
            "title_gu": "ભારત ઇલેક્ટ્રોનિક્સ લિમિટેડ (BEL) સોફ્ટવેર એન્જિનિયર ભરતી ૨૦૨૬ (૧૧૦ જગ્યાઓ - સંરક્ષણ પીએસયુ)",
            "organization": "Bharat Electronics Limited (BEL)",
            "department": "Software Division / Defence Radar & Communications Unit",
            "gov_level": "Central",
            "state": "All India",
            "district": "All India",
            "board_category": "PSU",
            "vacancies": 110,
            "qualification": "B.E. / B.Tech in Computer Science / Information Science / Computer Technology with First Class",
            "qualification_level": "Engineering",
            "age_min": 18,
            "age_max": 28,
            "age_relaxation_text": "OBC: +3 yrs, SC/ST: +5 yrs, PwD: +10 yrs",
            "salary_text": "CTC ₹11.5 LPA (₹40,000 - ₹1,40,000 E-II Grade) + Performance Related Pay (PRP)",
            "start_date": past_date(8),
            "last_date": future_date(22),
            "exam_date": "Written Test & Technical Interview: January 2027",
            "notification_number": "BEL/SDE/CS/2026/01",
            "notification_pdf_url": "https://bel-india.in/Documentviews.aspx?fileName=BEL_CS_2026.pdf",
            "apply_url": "https://bel-india.in/CareersGrid.aspx",
            "official_website": "https://bel-india.in",
            "application_fee": "General/OBC: ₹472. SC/ST/PwD: ₹0",
            "selection_process": "Written Test (85% weightage) -> Technical Interview (15% weightage).",
            "syllabus_summary": "C/C++, Java, Embedded Software Development, Real-Time Operating Systems (RTOS), Computer Networks, Linux Kernel.",
            "source": "BEL Official Portal",
            "is_active": 1,
            "featured": 0,
            "selection_mode": "written_exam",
            "job_category": "psu",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "C++, Java, RTOS, Linux Kernel, Socket Programming, Algorithms",
            "ctc_lpa": 11.5
        },

        # =====================================================================
        # 7. B.TECH CSE / IT JOBS - PREMIER PRIVATE TECH & MNCS (INDIA & GUJARAT)
        # =====================================================================
        {
            "title": "TCS National Qualifier Test (TCS NQT 2026) - Ninja, Digital & Prime Tracks (40,000+ Posts)",
            "title_gu": "ટાટા કન્સલ્ટન્સી સર્વિસીસ (TCS NQT ૨૦૨૬) નીન્જા, ડિજિટલ અને પ્રાઇમ ટ્રેક્સ ભરતી (૪૦,૦૦૦+ જગ્યાઓ - ગાંધીનગર કેમ્પસ)",
            "organization": "Tata Consultancy Services (TCS)",
            "department": "TCS Global Delivery Centres (Infocity Gandhinagar, Garima Park & Pan-India)",
            "gov_level": "Private",
            "state": "All India",
            "district": "ગાંધીનગર",
            "board_category": "Corporate",
            "vacancies": 40000,
            "qualification": "B.E. / B.Tech in CSE, IT, AI/ML, Data Science, Software Engineering or MCA (2024, 2025, 2026 Batches allowed with min 60%)",
            "qualification_level": "Engineering",
            "age_min": 18,
            "age_max": 28,
            "age_relaxation_text": "Open to all candidates meeting academic eligibility",
            "salary_text": "Ninja: ₹3.6 LPA | Digital: ₹7.2 LPA | Prime: ₹9.0 LPA (Based on NQT Score performance)",
            "start_date": past_date(15),
            "last_date": future_date(24),
            "exam_date": "TCS iON National Qualifier Test (In-centre CBT): December 2026 across Gujarat Centres",
            "notification_number": "TCS/NQT/FY26/PHASE-1",
            "notification_pdf_url": "https://www.tcs.com/careers/india/tcs-national-qualifier-test-details.pdf",
            "apply_url": "https://nextstep.tcs.com/campus",
            "official_website": "https://www.tcs.com/careers",
            "application_fee": "Free of Cost on TCS NextStep Portal (₹0)",
            "selection_process": "Stage 1: TCS NQT Online Test (Part A Foundation: Numerical, Verbal, Reasoning + Part B Advanced: Advanced Quantitative, Advanced Reasoning, 2 Hands-on Coding questions in C/C++/Java/Python) -> Stage 2: Technical & HR Interview.",
            "syllabus_summary": "Data Structures, Algorithms, Dynamic Programming, Arrays, Strings, Trees, Graphs, DBMS, SQL, Object-Oriented Design.",
            "source": "TCS NextStep Official",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "coding_test",
            "job_category": "private",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "Python, Java, C++, DSA, SQL, Web Technologies, Cloud",
            "ctc_lpa": 9.0
        },
        {
            "title": "Infosys Specialist Programmer (SP) & System Engineer Off-Campus Drive 2026 (25,000+ Posts)",
            "title_gu": "ઇન્ફોસિસ (Infosys) સ્પેશિયાલિસ્ટ પ્રોગ્રામર (SP ₹૯.૫ લાખ) & સિસ્ટમ એન્જિનિયર ભરતી ૨૦૨૬ (૨૫,૦૦૦+ જગ્યાઓ)",
            "organization": "Infosys Limited",
            "department": "Engineering Services & Digital Transformation Units (Ahmedabad / SEZ Gandhinagar Hub)",
            "gov_level": "Private",
            "state": "All India",
            "district": "ગાંધીનગર",
            "board_category": "Corporate",
            "vacancies": 25000,
            "qualification": "B.E. / B.Tech / M.Tech in Computer Science, Information Technology, Electronics or MCA with min 60% marks",
            "qualification_level": "Engineering",
            "age_min": 18,
            "age_max": 28,
            "age_relaxation_text": "Open to all passing batches 2024 to 2026",
            "salary_text": "Specialist Programmer (SP): ₹9.5 LPA | Digital Specialist Engineer (DSE): ₹6.5 LPA | System Engineer: ₹3.6 LPA",
            "start_date": past_date(12),
            "last_date": future_date(20),
            "exam_date": "Online HackWithInfy / InfyTQ Proctored Coding Rounds: December 2026",
            "notification_number": "INFY/CAMPUS/2026/01",
            "notification_pdf_url": "https://www.infosys.com/careers/graduates/documents/campus-recruitment-guide.pdf",
            "apply_url": "https://career.infosys.com/joblist",
            "official_website": "https://www.infosys.com",
            "application_fee": "Free (₹0)",
            "selection_process": "Proctored Online Coding Assessment (3 Advanced DSA Problems: DP, Graphs, Segment Trees) -> Technical Interview -> HR Round.",
            "syllabus_summary": "Advanced Algorithms, Data Structures, Greedy Algorithms, Dynamic Programming, Database Management, REST APIs.",
            "source": "Infosys Careers Portal",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "coding_test",
            "job_category": "private",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "Java, Python, C++, Dynamic Programming, Graphs, Microservices, Spring Boot",
            "ctc_lpa": 9.5
        },
        {
            "title": "Reliance Jio Platforms Graduate Engineer Trainee (GET - Cloud & Software) 2026 (1,200 Posts)",
            "title_gu": "રિલાયન્સ જીઓ (Jio Platforms) ગ્રેજ્યુએટ એન્જિનિયર તાલીમાર્થી (સોફ્ટવેર & 5G ક્લાઉડ) ભરતી ૨૦૨૬ (૧,૨૦૦ જગ્યાઓ)",
            "organization": "Jio Platforms Limited / Reliance Industries",
            "department": "Jio 5G Cloud Core & Artificial Intelligence Development Hubs (Ahmedabad / Navi Mumbai)",
            "gov_level": "Private",
            "state": "All India",
            "district": "અમદાવાદ",
            "board_category": "Corporate",
            "vacancies": 1200,
            "qualification": "B.Tech / B.E. in Computer Science, Information Technology, AI/Data Science with min 6.5 CGPA",
            "qualification_level": "Engineering",
            "age_min": 18,
            "age_max": 26,
            "age_relaxation_text": "2025 and 2026 graduating batches",
            "salary_text": "CTC ₹6.5 LPA to ₹8.5 LPA + Performance Bonus + Reliance Health Insurance & Employee Benefits",
            "start_date": past_date(10),
            "last_date": future_date(26),
            "exam_date": "Online HackerEarth Assessment & Technical Video Interview: December 2026",
            "notification_number": "JIO/GET/2026/CS",
            "notification_pdf_url": "https://careers.jio.com/documents/GET_Program_Brochure_2026.pdf",
            "apply_url": "https://careers.jio.com",
            "official_website": "https://careers.jio.com",
            "application_fee": "₹0 (Free)",
            "selection_process": "Online Aptitude + Coding Assessment (2 Coding Questions) -> Technical Interview (System Architecture & DSA) -> HR Round.",
            "syllabus_summary": "Core Java, Python, Golang, Microservices, Kubernetes, Docker, 5G Network fundamentals, RESTful APIs.",
            "source": "Jio Careers Official",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "coding_test",
            "job_category": "private",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "Java, Python, Golang, Docker, Kubernetes, Microservices, React",
            "ctc_lpa": 8.5
        },
        {
            "title": "Adani Digital Labs Associate Software Engineer Recruitment 2026 (350 Posts)",
            "title_gu": "અદાણી ડિજિટલ લેબ્સ (Adani Digital) એસોસિએટ સોફ્ટવેર એન્જિનિયર ભરતી ૨૦૨૬ (૩૫૦ જગ્યાઓ - અદાણી શાંતિગ્રામ અમદાવાદ)",
            "organization": "Adani Enterprises Limited - Adani Digital Labs",
            "department": "Consumer Tech & SuperApp Development Centre, Adani Shantigram, Ahmedabad",
            "gov_level": "Private",
            "state": "Gujarat",
            "district": "અમદાવાદ",
            "board_category": "Corporate",
            "vacancies": 350,
            "qualification": "B.E. / B.Tech in CSE / IT / Software Engineering or equivalent with strong problem solving skills",
            "qualification_level": "Engineering",
            "age_min": 18,
            "age_max": 28,
            "age_relaxation_text": "Fresher and up to 2 years experience welcome",
            "salary_text": "CTC ₹7.0 LPA to ₹12.0 LPA (Depending on Coding Round Performance) + Relocation Assistance",
            "start_date": past_date(8),
            "last_date": future_date(22),
            "exam_date": "Online Technical Coding Assessment & Virtual Interview Rounds: December 2026",
            "notification_number": "ADANI/DIGITAL/ASE/2026",
            "notification_pdf_url": "https://www.adani.com/careers/digital_labs_ase_2026.pdf",
            "apply_url": "https://www.adani.com/careers",
            "official_website": "https://www.adani.com",
            "application_fee": "₹0 (Free)",
            "selection_process": "1. Online DSA Coding Round -> 2. Technical System Design & OOP Interview -> 3. Cultural Fitment & HR Round.",
            "syllabus_summary": "Data Structures & Algorithms, Object-Oriented Design, High Concurrency handling, React Native / Flutter, Node.js / Golang, AWS Cloud.",
            "source": "Adani Careers Official Portal",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "coding_test",
            "job_category": "private",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "React, Node.js, Golang, AWS, Microservices, PostgreSQL, Kafka",
            "ctc_lpa": 12.0
        },
        {
            "title": "GIFT City FinTech Companies Software Developer & Blockchain Engineer 2026 (450 Posts)",
            "title_gu": "ગિફ્ટ સિટી (GIFT City Gandhinagar) ફિનટેક કંપનીઓ સોફ્ટવેર ડેવલપર અને બ્લોકચેન એન્જિનિયર ભરતી ૨૦૨૬ (૪૫૦ જગ્યાઓ)",
            "organization": "GIFT City FinTech Consortium (Global Financial Tech Hub)",
            "department": "International Financial Services Centre (IFSC), GIFT City, Gandhinagar, Gujarat",
            "gov_level": "Private",
            "state": "Gujarat",
            "district": "ગાંધીનગર",
            "board_category": "Corporate",
            "vacancies": 450,

            "qualification": "B.Tech / B.E. in Computer Science / IT / Mathematics & Computing with knowledge of FinTech architecture",
            "qualification_level": "Engineering",
            "age_min": 20,
            "age_max": 32,
            "age_relaxation_text": "Open to freshers & experienced tech engineers",
            "salary_text": "CTC ₹7.5 LPA to ₹16.0 LPA + Performance Stock Incentives + Tax Benefits under IFSC norms",
            "start_date": past_date(11),
            "last_date": future_date(28),
            "exam_date": "Online Hackathon & Technical Interview Drive: December 2026",
            "notification_number": "GIFT/FINTECH/2026/02",
            "notification_pdf_url": "https://www.giftgujarat.in/careers/fintech_developer_2026.pdf",
            "apply_url": "https://www.giftgujarat.in/careers",
            "official_website": "https://www.giftgujarat.in",
            "application_fee": "₹0 (Free)",
            "selection_process": "Online FinTech Coding Hackathon -> Technical Architecture Interview -> Offer rollout.",
            "syllabus_summary": "Financial APIs, Microservices, Solidity / Ethereum, Cryptographic protocols, High Frequency Trading (HFT) architectures, Redis, Kafka.",
            "source": "GIFT City Official Portal",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "coding_test",
            "job_category": "private",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "Java, Python, FinTech APIs, Blockchain, Microservices, Kafka, Redis",
            "ctc_lpa": 16.0
        },
        {
            "title": "Wipro Elite National Talent Hunt (ENTH) & Wipro Turbo 2026 (15,000+ Posts)",
            "title_gu": "વિપ્રો (Wipro Limited) એલાઇટ નેશનલ ટેલેન્ટ હન્ટ અને ટર્બો સોફ્ટવેર એન્જિનિયર ભરતી ૨૦૨૬ (૧૫,૦૦૦+ જગ્યાઓ)",
            "organization": "Wipro Limited",
            "department": "Enterprise Cloud & Cyber Security Delivery Units",
            "gov_level": "Central",
            "state": "All India",
            "district": "All India",
            "board_category": "Central",
            "vacancies": 15000,
            "qualification": "B.E. / B.Tech / 5-Year Integrated M.Tech in CS, IT, Electronics with min 60% marks",
            "qualification_level": "Engineering",
            "age_min": 18,
            "age_max": 28,
            "age_relaxation_text": "Passing out batch 2024, 2025, 2026",
            "salary_text": "Elite: ₹3.5 LPA | Turbo: ₹6.5 LPA (Based on Assessment Score)",
            "start_date": past_date(14),
            "last_date": future_date(18),
            "exam_date": "Online Assessment: December 2026",
            "notification_number": "WIPRO/ENTH/2026/01",
            "notification_pdf_url": "https://careers.wipro.com/elite_talent_hunt_2026.pdf",
            "apply_url": "https://careers.wipro.com",
            "official_website": "https://careers.wipro.com",
            "application_fee": "₹0 (Free)",
            "selection_process": "Aptitude Test + Written Communication Test + Online Programming Test (2 questions) -> Technical Interview.",
            "syllabus_summary": "Quantitative Aptitude, Logical Reasoning, Coding in Java/C++/Python, OOP concepts.",
            "source": "Wipro Careers Official",
            "is_active": 1,
            "featured": 0,
            "selection_mode": "coding_test",
            "job_category": "private",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "Java, Python, C++, SQL, Algorithms",
            "ctc_lpa": 6.5
        },
        {
            "title": "L&T Technology Services (LTTS) Embedded & Software Engineer Drive 2026 (400 Posts)",
            "title_gu": "એલ એન્ડ ટી ટેકનોલોજી સર્વિસીસ (LTTS વડોદરા & અમદાવાદ) એમ્બેડેડ અને સોફ્ટવેર એન્જિનિયર ભરતી ૨૦૨૬ (૪૦૦ જગ્યાઓ)",
            "organization": "L&T Technology Services Limited (LTTS)",
            "department": "Digital & Software Engineering Delivery Centre, Vadodara Knowledge City & GIFT City Hub",
            "gov_level": "State",
            "state": "Gujarat",
            "district": "વડોદરા",
            "board_category": "State",
            "vacancies": 400,
            "qualification": "B.E. / B.Tech in CSE, IT, Electronics & Communication with min 60% marks",
            "qualification_level": "Engineering",
            "age_min": 18,
            "age_max": 28,
            "age_relaxation_text": "Freshers and 1-2 years experience",
            "salary_text": "CTC ₹4.5 LPA to ₹8.0 LPA + Performance Bonus",
            "start_date": past_date(7),
            "last_date": future_date(25),
            "exam_date": "Written Technical Exam & Interview at LTTS Vadodara Campus: December 2026",
            "notification_number": "LTTS/VAD/CS/2026/02",
            "notification_pdf_url": "https://www.ltts.com/careers/embedded_software_engineer_2026.pdf",
            "apply_url": "https://www.ltts.com/careers",
            "official_website": "https://www.ltts.com",
            "application_fee": "₹0 (Free)",
            "selection_process": "Technical Written Test -> Technical Coding Interview -> HR Round.",
            "syllabus_summary": "C/C++, Python, Linux OS, Device Drivers, IoT Protocols (MQTT, CoAP), Microcontrollers.",
            "source": "LTTS Careers Official",
            "is_active": 1,
            "featured": 0,
            "selection_mode": "coding_test",
            "job_category": "private",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "C, C++, Python, Embedded Linux, IoT, RTOS, Git",
            "ctc_lpa": 8.0
        },
        # =====================================================================
        # 7. GUJARAT & REGIONAL BANKING, MUNICIPAL & POSTAL EXPANSIONS
        # =====================================================================
        {
            "title": "IBPS Regional Rural Banks (RRB XIII) - Baroda Gujarat Gramin Bank & Saurashtra Gramin Bank Office Assistant & Officer Scale-I 2026 (9,995 Posts)",
            "title_gu": "IBPS પ્રાદેશિક ગ્રામીણ બેંક (RRB XIII) - બરોડા ગુજરાત ગ્રામીણ બેંક & સૌરાષ્ટ્ર ગ્રામીણ બેંક ઓફિસ આસિસ્ટન્ટ & ઓફિસર સ્કેલ-૧ ભરતી ૨૦૨૬ (૯,૯૯૫ જગ્યાઓ)",
            "organization": "Institute of Banking Personnel Selection (IBPS) & Regional Rural Banks of Gujarat",
            "department": "Baroda Gujarat Gramin Bank (BGGB) & Saurashtra Gramin Bank (SGB)",
            "gov_level": "Central",
            "state": "Gujarat",
            "district": "All Gujarat",
            "board_category": "Banking",
            "vacancies": 9995,
            "qualification": "Bachelor's Degree in any discipline from a recognized University (B.Tech / B.E. / B.Sc / B.Com / B.A.) + Proficiency in Gujarati Local Language + Working Knowledge of Computer",
            "qualification_level": "Graduate",
            "age_min": 18,
            "age_max": 30,
            "age_relaxation_text": "OBC/SEBC: +3 yrs, SC/ST: +5 yrs, PwBD: +10 yrs",
            "salary_text": "Office Assistant: ₹32,000 - ₹38,000/mo | Officer Scale-I: ₹58,000 - ₹66,000/mo (7th CPC Equivalent)",
            "start_date": past_date(10),
            "last_date": future_date(20),
            "exam_date": "Preliminary Online CBT: August 2026 | Mains Exam: September 2026",
            "notification_number": "IBPS/CRP-RRBs-XIII/2026",
            "notification_pdf_url": "https://www.ibps.in/crp-rrb-xiii-official-notification-2026.pdf",
            "apply_url": "https://ibpsonline.ibps.in/crprrbxiiijun26/",
            "official_website": "https://www.ibps.in",
            "application_fee": "General/OBC/EWS: ₹850. SC/ST/PwBD: ₹175",
            "selection_process": "Prelims Online CBT -> Mains Online CBT -> Local Language Test (Gujarati) -> Document Verification.",
            "syllabus_summary": "Reasoning Ability (40 Qs, 50 Marks), Quantitative Aptitude / Numerical Ability (40 Qs, 50 Marks), General Awareness with special reference to Gujarat Banking, English/Hindi Language, Computer Knowledge (40 Qs, 20 Marks).",
            "source": "IBPS Official Gazette",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "written_exam",
            "job_category": "government",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "Core Banking, SQL, Python, Excel, Finacle",
            "ctc_lpa": 7.5
        },
        {
            "title": "Gujarat State Cooperative Bank (GSC Bank) & DCCB Gujarat Junior Clerk, Cashier & IT Assistant 2026 (1,250 Posts)",
            "title_gu": "ગુજરાત સ્ટેટ કો-ઓપરેટિવ બેંક (GSC બેંક) અને જિલ્લા સહકારી બેંકો જુનિયર ક્લાર્ક, કેશિયર અને આઈટી આસિસ્ટન્ટ ભરતી ૨૦૨૬ (૧,૨૫૦ જગ્યાઓ)",
            "organization": "The Gujarat State Co-Operative Bank Ltd. (GSC Bank)",
            "department": "State Cooperative Banking Network, Ahmedabad, Surat, Rajkot, Vadodara, Mehsana",
            "gov_level": "State",
            "state": "Gujarat",
            "district": "All Gujarat",
            "board_category": "Banking",
            "vacancies": 1250,
            "qualification": "Graduate in any discipline (B.Tech / B.E. / B.Com / B.Sc / BCA) with min 50% marks + Basic Knowledge of Computer Operations",
            "qualification_level": "Graduate",
            "age_min": 20,
            "age_max": 32,
            "age_relaxation_text": "Gujarat Reserved Categories: +5 yrs, Female: +5 yrs",
            "salary_text": "₹24,000 - ₹34,000/month initial pay scale with DA, HRA and Provident Fund",
            "start_date": past_date(8),
            "last_date": future_date(24),
            "exam_date": "Online Written CBT in Ahmedabad, Vadodara, Surat & Rajkot: November 2026",
            "notification_number": "GSCB/HR/RECRUIT/2026/03",
            "notification_pdf_url": "https://gscbank.co.in/careers/clerk_recruitment_2026.pdf",
            "apply_url": "https://gscbank.co.in/careers",
            "official_website": "https://gscbank.co.in",
            "application_fee": "General/SEBC: ₹500. SC/ST/Female: ₹250",
            "selection_process": "Online Objective Exam (100 Marks) -> Personal Interview -> Merit List.",
            "syllabus_summary": "General Knowledge & Gujarat Affairs (25 Qs), English Language (25 Qs), Reasoning & Quantitative Aptitude (30 Qs), Banking & Computer Awareness (20 Qs).",
            "source": "GSC Bank Official",
            "is_active": 1,
            "featured": 0,
            "selection_mode": "written_exam",
            "job_category": "government",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "Banking Tech, SQL, Excel, IT Support",
            "ctc_lpa": 4.2
        },
        {
            "title": "India Post Payments Bank (IPPB) Executive & IT Project Lead Recruitment 2026 (350 Posts)",
            "title_gu": "ઇન્ડિયા પોસ્ટ પેમેન્ટ્સ બેંક (IPPB) એક્ઝિક્યુટિવ અને આઇટી પ્રોજેક્ટ લીડ ભરતી ૨૦૨૬ (૩૫૦ જગ્યાઓ)",
            "organization": "India Post Payments Bank Limited (IPPB) / Department of Posts",
            "department": "FinTech & Digital Delivery Division, Ministry of Communications",
            "gov_level": "Central",
            "state": "Gujarat",
            "district": "All Gujarat",
            "board_category": "Postal",
            "vacancies": 350,
            "qualification": "Graduation in any discipline, preference to B.E. / B.Tech (Computer Science / IT) or BCA/MCA",
            "qualification_level": "Graduate",
            "age_min": 21,
            "age_max": 35,
            "age_relaxation_text": "SC/ST: +5 yrs, OBC: +3 yrs, PwD: +10 yrs",
            "salary_text": "Lump sum ₹30,000 to ₹55,000/- per month + Performance Incentive & Travel Allowance",
            "start_date": past_date(5),
            "last_date": future_date(22),
            "exam_date": "Online Computer-Based Test / Direct Interview: October 2026",
            "notification_number": "IPPB/CO/HR/REC/2026-27/02",
            "notification_pdf_url": "https://www.ippbonline.com/documents/20123/executive_recruitment_2026.pdf",
            "apply_url": "https://www.ippbonline.com/web/ippb/current-openings",
            "official_website": "https://www.ippbonline.com",
            "application_fee": "SC/ST/PWD: ₹150. All others: ₹750",
            "selection_process": "Online Examination (Objective) followed by Interview / Group Discussion.",
            "syllabus_summary": "Reasoning, English Language, Quantitative Aptitude, General Awareness with special reference to Banking & Postal Financial Services, Computer & Digital Payment Ecosystem.",
            "source": "IPPB Careers Official",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "written_exam",
            "job_category": "government",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "UPI, IMPS, Digital Banking, Cyber Security, SQL, Python",
            "ctc_lpa": 6.6
        },
        {
            "title": "Rajkot & Vadodara Municipal Corporations (RMC & VMC) Assistant Engineer (IT & Civil) & Junior Town Planner 2026 (320 Posts)",
            "title_gu": "રાજકોટ અને વડોદરા મહાનગરપાલિકા (RMC & VMC) આસિસ્ટન્ટ એન્જિનિયર (આઇટી & સિવિલ) અને જુનિયર ટાઉન પ્લાનર ભરતી ૨૦૨૬ (૩૨૦ જગ્યાઓ)",
            "organization": "Rajkot Municipal Corporation (RMC) & Vadodara Municipal Corporation (VMC)",
            "department": "Smart City Mission & Information Technology Directorate",
            "gov_level": "State",
            "state": "Gujarat",
            "district": "રાજકોટ",
            "board_category": "AMC/SMC",
            "vacancies": 320,
            "qualification": "B.E. / B.Tech in Computer Engineering / Information Technology / Civil Engineering with minimum 55% from recognized University",
            "qualification_level": "Engineering",
            "age_min": 18,
            "age_max": 36,
            "age_relaxation_text": "Gujarat Reserved Quotas: +5 yrs, Women: +5 yrs",
            "salary_text": "₹40,800/- Fix Pay for 5 Years -> 7th CPC Level-8 (₹44,900 - ₹1,42,400)",
            "start_date": past_date(9),
            "last_date": future_date(18),
            "exam_date": "Written OMR Examination: November 2026",
            "notification_number": "RMC-VMC/ENGG/2026/04",
            "notification_pdf_url": "https://www.rmc.gov.in/Recruitment/AE_IT_Civil_2026.pdf",
            "apply_url": "https://www.rmc.gov.in/Recruitment",
            "official_website": "https://www.rmc.gov.in",
            "application_fee": "General: ₹500. Reserved Categories: ₹250",
            "selection_process": "Part A: General Knowledge & Gujarati Language (50 Marks) + Part B: Concerned Engineering Specialization (150 Marks).",
            "syllabus_summary": "Computer Networks, Database Management Systems, Smart City IoT Infrastructure, Web Technologies, Software Engineering, Municipal Governance Act.",
            "source": "RMC Official Gazette",
            "is_active": 1,
            "featured": 1,
            "selection_mode": "written_exam",
            "job_category": "government",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "IoT, Smart City Solutions, GIS, PostgreSQL, Networking",
            "ctc_lpa": 5.4
        },
        {
            "title": "Gujarat Pollution Control Board (GPCB) Scientific Assistant & Assistant Environmental Engineer 2026 (210 Posts)",
            "title_gu": "ગુજરાત પ્રદૂષણ નિયંત્રણ બોર્ડ (GPCB ગાંધીનગર) સાયન્ટિફિક આસિસ્ટન્ટ & આસિસ્ટન્ટ એન્વાયર્નમેન્ટલ એન્જિનિયર ભરતી ૨૦૨૬ (૨૧૦ જગ્યાઓ)",
            "organization": "Gujarat Pollution Control Board (GPCB), Gandhinagar",
            "department": "Forests & Environment Department, Government of Gujarat",
            "gov_level": "State",
            "state": "Gujarat",
            "district": "ગાંધીનગર",
            "board_category": "OJAS",
            "vacancies": 210,
            "qualification": "B.E. / B.Tech in Environmental / Chemical / Computer Engineering or M.Sc. in Environmental Science / Chemistry with min 55% marks",
            "qualification_level": "Engineering",
            "age_min": 18,
            "age_max": 35,
            "age_relaxation_text": "SEBC/SC/ST: +5 yrs, Women: +5 yrs",
            "salary_text": "₹38,090/- Fix Pay for 5 Years -> 7th CPC Level-7 (₹39,900 - ₹1,26,600)",
            "start_date": past_date(6),
            "last_date": future_date(26),
            "exam_date": "Written OMR Exam conducted via GPSC/OJAS: December 2026",
            "notification_number": "GPCB/EST/2026/01",
            "notification_pdf_url": "https://gpcb.gujarat.gov.in/sites/default/files/recruitment_2026.pdf",
            "apply_url": "https://ojas.gujarat.gov.in",
            "official_website": "https://gpcb.gujarat.gov.in",
            "application_fee": "General: ₹100. Reserved Categories: ₹0 (Exempted)",
            "selection_process": "Written Competitive Examination (OMR) -> Document Verification at Paryavaran Bhavan, Gandhinagar.",
            "syllabus_summary": "General Studies, Constitution of India, Environment Protection Acts, Water & Air Quality Monitoring, Environmental Data Analysis.",
            "source": "GPCB Gandhinagar Gazette",
            "is_active": 1,
            "featured": 0,
            "selection_mode": "written_exam",
            "job_category": "government",
            "is_btech_cse": 1,
            "experience_level": "fresher",
            "tech_stack": "Environmental Data Analytics, Python, GIS, Sensor Networks",
            "ctc_lpa": 5.2
        }
    ]

    return jobs

