"""
Batch 3 of Major Private Employers in India:
- Global Investment Banking Tech Centers (Goldman Sachs, JP Morgan, Morgan Stanley, Barclays, Wells Fargo, HSBC, Citi, Deutsche Bank)
- Big 4 & Consulting (Deloitte, PwC, EY, KPMG)
- Semiconductor & Deep Tech (Micron Sanand Gujarat, AMD, Texas Instruments, Applied Materials, Tata Electronics Sanand)
- Telecom & 5G (Bharti Airtel, Ericsson, Nokia)
- Aviation & Airlines (IndiGo, Air India, MakeMyTrip)
- Global Retail GCCs (Walmart Global Tech, Target India)
"""

BATCH3_COMPANIES = [
    # -------------------------------------------------------------------------
    # GLOBAL INVESTMENT BANKS & FINANCIAL GCCs IN INDIA
    # -------------------------------------------------------------------------
    {
        "title": "Goldman Sachs India Campus New Analyst & Software Engineer 2026 (650 Posts)",
        "title_gu": "ગોલ્ડમેન સૅક્સ ઇન્ડિયા સોફ્ટવેર એન્જિનિયર અને ન્યૂ એનાલિસ્ટ ૨૦૨૬ (૬૫૦ જગ્યાઓ)",
        "organization": "Goldman Sachs Services India Private Limited",
        "department": "Global Investment Research, Quantitative Execution & Core Engineering",
        "gov_level": "Private",
        "state": "All India",
        "district": "Bengaluru",
        "board_category": "Corporate",
        "vacancies": 650,
        "qualification": "B.E. / B.Tech / M.Tech in CSE, IT, Mathematics & Computing, ECE or MCA",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹24.0 LPA to ₹36.0 LPA + Performance Bonus",
        "notification_number": "GS-IN/ENGG/2026",
        "apply_url": "https://www.goldmansachs.com/careers",
        "official_website": "https://www.goldmansachs.com",
        "selection_process": "Online Aptitude & Coding Assessment -> Technical Architecture Rounds -> Managing Director Interview",
        "syllabus_summary": "Data Structures, Algorithms, Discrete Math, Concurrency, Java/C++, System Design",
        "source": "Goldman Sachs Official Careers",
        "selection_mode": "coding_test",
        "job_category": "bfsi",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Java, C++, Python, Slang/SecDB, React, Spring Boot, Microservices",
        "ctc_lpa": 36.0,
        "days_ago": 7,
        "days_ahead": 35
    },
    {
        "title": "JPMorgan Chase & Co. Software Engineer Program (SEP) 2026 (1,200 Posts)",
        "title_gu": "જેપીમોર્ગન ચેઝ સોફ્ટવેર એન્જિનિયર પ્રોગ્રામ (SEP) ૨૦૨૬ (૧,૨૦૦ જગ્યાઓ)",
        "organization": "JPMorgan Chase & Co. India Tech Centres",
        "department": "Corporate & Investment Bank (CIB), Asset & Wealth Tech",
        "gov_level": "Private",
        "state": "All India",
        "district": "Mumbai",
        "board_category": "Corporate",
        "vacancies": 1200,
        "qualification": "B.E. / B.Tech in Computer Science / IT / Circuit Branches with min 65% aggregate",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹19.5 LPA to ₹28.0 LPA + Relocation Allowance",
        "notification_number": "JPMC-SEP/IND/2026",
        "apply_url": "https://careers.jpmorgan.com",
        "official_website": "https://www.jpmorganchase.com",
        "selection_process": "Coding Challenge (HackerRank) -> HireVue Video Interview -> Code for Good Hackathon / Superday",
        "syllabus_summary": "Algorithms, Data Structures, OOP, SQL, Java/Python, Agile Software Delivery",
        "source": "JPMorgan Chase Careers",
        "selection_mode": "coding_test",
        "job_category": "bfsi",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Java, Python, AWS, Spring Cloud, Kafka, Docker, Kubernetes, PostgreSQL",
        "ctc_lpa": 28.0,
        "days_ago": 10,
        "days_ahead": 40
    },
    {
        "title": "Morgan Stanley India Technology Analyst (Full-Time) 2026 (500 Posts)",
        "title_gu": "મોર્ગન સ્ટેનલી ઇન્ડિયા ટેકનોલોજી એનાલિસ્ટ ભરતી ૨૦૨૬ (૫૦૦ જગ્યાઓ)",
        "organization": "Morgan Stanley Advantage Services India",
        "department": "Institutional Securities Technology & Global Wealth Tech",
        "gov_level": "Private",
        "state": "All India",
        "district": "Bengaluru",
        "board_category": "Corporate",
        "vacancies": 500,
        "qualification": "B.E. / B.Tech in CSE / IT / ECE with strong computer science fundamentals",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹22.0 LPA to ₹30.0 LPA + Annual Performance Incentive",
        "notification_number": "MS-IN/TECH/2026",
        "apply_url": "https://www.morganstanley.com/careers",
        "official_website": "https://www.morganstanley.com",
        "selection_process": "Online Assessment (CS Fundamentals & DSA) -> 3 Technical Rounds -> Vice President Final Round",
        "syllabus_summary": "Operating Systems, Computer Networks, Database Internals, DSA, Distributed Systems",
        "source": "Morgan Stanley Official",
        "selection_mode": "coding_test",
        "job_category": "bfsi",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "C++, Java, Python, Linux Internals, Low Latency Messaging, Sybase/Postgres",
        "ctc_lpa": 30.0,
        "days_ago": 12,
        "days_ahead": 32
    },
    {
        "title": "Barclays Global Service Centre Graduate Technology Analyst 2026 (750 Posts)",
        "title_gu": "બાર્કલેઝ ગ્લોબલ સર્વિસ સેન્ટર ગ્રેજ્યુએટ ટેકનોલોજી એનાલિસ્ટ ૨૦૨૬ (૭૫૦ જગ્યાઓ)",
        "organization": "Barclays Global Service Centre India",
        "department": "Consumer Banking & Payments, Cloud Platforms & Cybersecurity",
        "gov_level": "Private",
        "state": "All India",
        "district": "Pune",
        "board_category": "Corporate",
        "vacancies": 750,
        "qualification": "B.E. / B.Tech / MCA in Computer Science / IT / Electronics",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹14.0 LPA to ₹19.5 LPA + Health Cover",
        "notification_number": "BARC-IN/GRAD/2026",
        "apply_url": "https://home.barclays/careers",
        "official_website": "https://home.barclays",
        "selection_process": "Online Technical & Cognitive Assessment -> Technical Interview -> Values Round",
        "syllabus_summary": "Core Java, REST APIs, Microservices, SQL, Git, Linux, Financial Domain Basics",
        "source": "Barclays Careers Official",
        "selection_mode": "coding_test",
        "job_category": "bfsi",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Java, Spring Boot, Angular, AWS Cloud, Kafka, Oracle, Jenkins",
        "ctc_lpa": 19.5,
        "days_ago": 14,
        "days_ahead": 36
    },
    {
        "title": "Wells Fargo India Technology Associate 2026 (800 Posts)",
        "title_gu": "વેલ્સ ફાર્ગો ઇન્ડિયા ટેકનોલોજી એસોસિએટ ૨૦૨૬ (૮૦૦ જગ્યાઓ)",
        "organization": "Wells Fargo International Solutions Private Limited",
        "department": "Enterprise Global Services (EGS) Tech & Cyber Defense",
        "gov_level": "Private",
        "state": "All India",
        "district": "Hyderabad",
        "board_category": "Corporate",
        "vacancies": 800,
        "qualification": "B.E. / B.Tech in CSE / IT / ECE or MCA with min 60% marks",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹13.5 LPA to ₹18.0 LPA + Retention Bonus",
        "notification_number": "WF-EGS/2026/04",
        "apply_url": "https://www.wellsfargo.com/about/careers",
        "official_website": "https://www.wellsfargo.com",
        "selection_process": "Online Coding & Aptitude Test -> Technical Interview -> Behavioral Assessment",
        "syllabus_summary": "Data Structures, Cloud Engineering, RDBMS, Java/Python, Security Principles",
        "source": "Wells Fargo Careers",
        "selection_mode": "coding_test",
        "job_category": "bfsi",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Java, Python, Azure Cloud, Microservices, MongoDB, Splunk",
        "ctc_lpa": 18.0,
        "days_ago": 9,
        "days_ahead": 31
    },
    {
        "title": "HSBC Technology India Software Engineer Trainee 2026 (900 Posts)",
        "title_gu": "એચએસબીસી ટેકનોલોજી ઇન્ડિયા સોફ્ટવેર એન્જિનિયર ટ્રેઇની ૨૦૨૬ (૯૦૦ જગ્યાઓ)",
        "organization": "HSBC Technology & Services India",
        "department": "Global Commercial Banking & Digital Wealth Platforms",
        "gov_level": "Private",
        "state": "All India",
        "district": "Pune",
        "board_category": "Corporate",
        "vacancies": 900,
        "qualification": "B.Tech / B.E. in Computer Science / IT / Electronics",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹11.5 LPA to ₹16.0 LPA + Banking Perquisites",
        "notification_number": "HSBC-TECH/2026",
        "apply_url": "https://www.hsbc.com/careers",
        "official_website": "https://www.hsbc.com",
        "selection_process": "Online Coding & Reasoning Assessment -> 2 Technical Rounds -> Senior Leadership Round",
        "syllabus_summary": "Java, Cloud Platforms, System Design, Modern UI, API Security",
        "source": "HSBC Careers Portal",
        "selection_mode": "coding_test",
        "job_category": "bfsi",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Java, Spring Boot, React, GCP/AWS, Docker, CI/CD",
        "ctc_lpa": 16.0,
        "days_ago": 11,
        "days_ahead": 34
    },
    {
        "title": "Citigroup India (Citi Technology) Technology Analyst 2026 (650 Posts)",
        "title_gu": "સિટી ટેકનોલોજી ઇન્ડિયા ટેકનોલોજી એનાલિસ્ટ ૨૦૨૬ (૬૫૦ જગ્યાઓ)",
        "organization": "Citigroup Global Services India Private Limited",
        "department": "Treasury & Trade Solutions (TTS) & Consumer Tech",
        "gov_level": "Private",
        "state": "All India",
        "district": "Chennai",
        "board_category": "Corporate",
        "vacancies": 650,
        "qualification": "B.E. / B.Tech in CSE / IT / ECE with min 60% throughout",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹15.0 LPA to ₹22.0 LPA + Performance Bonus",
        "notification_number": "CITI-TECH/2026/02",
        "apply_url": "https://jobs.citi.com",
        "official_website": "https://www.citi.com",
        "selection_process": "Online Coding & Aptitude Test -> Technical Rounds -> Director Interview",
        "syllabus_summary": "Data Structures, Algorithms, SQL, Java, Microservices Architecture, Cloud Basics",
        "source": "Citi Careers Official",
        "selection_mode": "coding_test",
        "job_category": "bfsi",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Java, Python, Angular, Microservices, OpenShift, Oracle",
        "ctc_lpa": 22.0,
        "days_ago": 13,
        "days_ahead": 37
    },
    {
        "title": "Deutsche Bank India Graduate Technology Trainee 2026 (450 Posts)",
        "title_gu": "ડોઇશ બેંક ઇન્ડિયા ગ્રેજ્યુએટ ટેકનોલોજી ટ્રેઇની ૨૦૨૬ (૪૫૦ જગ્યાઓ)",
        "organization": "Deutsche India Private Limited (DIPL)",
        "department": "Investment Bank Technology & Corporate Banking Platform",
        "gov_level": "Private",
        "state": "All India",
        "district": "Pune",
        "board_category": "Corporate",
        "vacancies": 450,
        "qualification": "B.Tech / B.E. / MCA in CSE / IT with good programming background",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹14.5 LPA to ₹20.0 LPA",
        "notification_number": "DB-INDIA/GRAD/2026",
        "apply_url": "https://careers.db.com",
        "official_website": "https://www.db.com",
        "selection_process": "Online Coding Round (HackerEarth) -> Tech Interview 1 -> Tech Interview 2 -> HR",
        "syllabus_summary": "Data Structures, Object Oriented Design, Multithreading, Database Optimizations",
        "source": "Deutsche Bank Careers",
        "selection_mode": "coding_test",
        "job_category": "bfsi",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Java, Python, C++, GCP, Spring, React, Oracle",
        "ctc_lpa": 20.0,
        "days_ago": 15,
        "days_ahead": 35
    },

    # -------------------------------------------------------------------------
    # BIG 4 CONSULTING & ADVISORY
    # -------------------------------------------------------------------------
    {
        "title": "Deloitte India Associate Analyst & Technology Consultant 2026 (4,500 Posts)",
        "title_gu": "ડેલોઇટ ઇન્ડિયા એસોસિએટ એનાલિસ્ટ અને ટેકનોલોજી કન્સલ્ટન્ટ ૨૦૨૬ (૪,૫૦૦ જગ્યાઓ)",
        "organization": "Deloitte Touche Tohmatsu India / Deloitte USI",
        "department": "Advisory, Cyber Security, Cloud Engineering & Artificial Intelligence",
        "gov_level": "Private",
        "state": "All India",
        "district": "અમદાવાદ",
        "board_category": "Corporate",
        "vacancies": 4500,
        "qualification": "B.E. / B.Tech in Any Stream / MCA / BCA / B.Sc IT with min 60%",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 29,
        "salary_text": "CTC ₹7.6 LPA to ₹12.5 LPA + Hybrid Work Policy",
        "notification_number": "DEL-IND/NLT/2026",
        "apply_url": "https://www2.deloitte.com/ui/en/careers/careers.html",
        "official_website": "https://www.deloitte.com",
        "selection_process": "Deloitte National Aptitude Test -> Technical Assessment -> Behavioral & Partner Interview",
        "syllabus_summary": "Quantitative Aptitude, Logical Reasoning, Verbal Ability, Technical MCQs (Cloud/SQL/Python)",
        "source": "Deloitte Official Careers",
        "selection_mode": "written_exam",
        "job_category": "it_services",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Cloud Consulting, Python, SQL, PowerBI, Salesforce, SAP, Cyber Risk",
        "ctc_lpa": 12.5,
        "days_ago": 8,
        "days_ahead": 32
    },
    {
        "title": "PricewaterhouseCoopers (PwC India) Technology Trainee Consultant 2026 (2,500 Posts)",
        "title_gu": "પીડબલ્યુસી ઇન્ડિયા (PwC) ટેકનોલોજી કન્સલ્ટન્ટ ટ્રેઇની ૨૦૨૬ (૨,૫૦૦ જગ્યાઓ)",
        "organization": "PwC India (PricewaterhouseCoopers)",
        "department": "Digital & Technology Consulting, Enterprise Applications & Risk",
        "gov_level": "Private",
        "state": "All India",
        "district": "All India",
        "board_category": "Corporate",
        "vacancies": 2500,
        "qualification": "B.Tech / B.E. in Any Branch / MCA with 60% aggregate",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹7.0 LPA to ₹11.5 LPA",
        "notification_number": "PWC-IN/DIGITAL/2026",
        "apply_url": "https://www.pwc.in/careers.html",
        "official_website": "https://www.pwc.in",
        "selection_process": "Cognitive & Aptitude Test -> Technical Coding & Case Study -> Partner Interview",
        "syllabus_summary": "Aptitude, Analytical Reasoning, Python/Java, Cloud Basics, Business Case Analysis",
        "source": "PwC Careers Portal",
        "selection_mode": "interview_assessment",
        "job_category": "it_services",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Oracle Cloud, SAP S/4HANA, Python, Azure, Data Analytics, Cybersecurity",
        "ctc_lpa": 11.5,
        "days_ago": 10,
        "days_ahead": 30
    },
    {
        "title": "Ernst & Young (EY India & GDS) Associate Software Engineer 2026 (3,200 Posts)",
        "title_gu": "અર્ન્સ્ટ એન્ડ યંગ (EY) એસોસિએટ સોફ્ટવેર એન્જિનિયર ૨૦૨૬ (૩,૨૦૦ જગ્યાઓ)",
        "organization": "Ernst & Young (EY Global Delivery Services India)",
        "department": "AI & Data Labs, Digital Assurance & Technology Consulting",
        "gov_level": "Private",
        "state": "All India",
        "district": "All India",
        "board_category": "Corporate",
        "vacancies": 3200,
        "qualification": "B.E. / B.Tech / MCA / M.Sc Computer Science",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹7.0 LPA to ₹11.0 LPA + Performance Bonus",
        "notification_number": "EY-GDS/ASE/2026",
        "apply_url": "https://www.ey.com/en_in/careers",
        "official_website": "https://www.ey.com",
        "selection_process": "EY Online Assessment -> Technical Discussion -> Senior Manager Video Round",
        "syllabus_summary": "Aptitude, Coding Fundamentals, Database Concepts, Cloud & Cybersecurity",
        "source": "EY Official Careers",
        "selection_mode": "coding_test",
        "job_category": "it_services",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Java, .NET Core, Azure, React, Power Automate, Cyber Defense",
        "ctc_lpa": 11.0,
        "days_ago": 12,
        "days_ahead": 35
    },
    {
        "title": "KPMG India Advisory Trainee & Tech Risk Analyst 2026 (1,800 Posts)",
        "title_gu": "કેપીએમજી ઇન્ડિયા (KPMG) એડવાઇઝરી ટ્રેઇની અને ટેક એનાલિસ્ટ ૨૦૨૬ (૧,૮૦૦ જગ્યાઓ)",
        "organization": "KPMG Global Services India (KGS)",
        "department": "Digital Lighthouse, Cyber Security & Management Consulting",
        "gov_level": "Private",
        "state": "All India",
        "district": "All India",
        "board_category": "Corporate",
        "vacancies": 1800,
        "qualification": "B.E. / B.Tech / MCA / Any Graduate with technical aptitude and min 60%",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹6.5 LPA to ₹10.5 LPA",
        "notification_number": "KPMG-KGS/2026/01",
        "apply_url": "https://home.kpmg/in/en/home/careers.html",
        "official_website": "https://home.kpmg",
        "selection_process": "Online Aptitude & Domain Test -> Group Discussion / Case Presentation -> HR",
        "syllabus_summary": "Quantitative, Logical, Verbal, Cloud & Information Security Basics",
        "source": "KPMG Careers",
        "selection_mode": "interview_assessment",
        "job_category": "it_services",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Python, SQL, AWS, Azure, Tableau, IT Auditing, Cyber Security",
        "ctc_lpa": 10.5,
        "days_ago": 14,
        "days_ahead": 33
    },

    # -------------------------------------------------------------------------
    # SEMICONDUCTOR & DEEP TECH (SANAND GUJARAT MEGA FAB & SILICON DESIGN)
    # -------------------------------------------------------------------------
    {
        "title": "Micron Technology India (Sanand Gujarat ATMP Facility) Trainee Engineer 2026 (1,500 Posts)",
        "title_gu": "માઇક્રોન ટેકનોલોજી ઇન્ડિયા (સાણંદ સેમિકન્ડક્ટર પ્લાન્ટ) ટ્રેઇની એન્જિનિયર ૨૦૨૬ (૧,૫૦૦ જગ્યાઓ)",
        "organization": "Micron Technology India Operations Private Limited",
        "department": "Sanand Semiconductor Assembly & Test (ATMP) Cleanroom Facility",
        "gov_level": "Private",
        "state": "Gujarat",
        "district": "અમદાવાદ",
        "board_category": "Corporate",
        "vacancies": 1500,
        "qualification": "B.E. / B.Tech in Electronics / Mechanical / Electrical / Computer Science / Chemical or M.Tech",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 29,
        "salary_text": "CTC ₹10.5 LPA to ₹18.0 LPA + Semiconductor Cleanroom Allowance",
        "notification_number": "MICRON-SANAND/ENGG/2026",
        "apply_url": "https://www.micron.com/careers",
        "official_website": "https://www.micron.com",
        "selection_process": "Online Technical & Semiconductor Fundamentals Assessment -> Technical Interview -> Plant Tour",
        "syllabus_summary": "VLSI Design, Semiconductor Physics, Wafer Packaging, Surface Mount Technology, Python automation",
        "source": "Micron Technology Careers Official",
        "selection_mode": "written_exam",
        "job_category": "gujarat_champions",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Semiconductor Packaging, Cleanroom Protocols, Python, LabVIEW, SCADA, Automated Test Equipment (ATE)",
        "ctc_lpa": 18.0,
        "days_ago": 5,
        "days_ahead": 45
    },
    {
        "title": "Tata Electronics Semiconductor (Sanand / Dholera Gujarat) Fab & OSAT Engineer Trainee 2026 (1,800 Posts)",
        "title_gu": "ટાટા ઇલેક્ટ્રોનિક્સ સેમિકન્ડક્ટર (સાણંદ અને ધોલેરા) ફેબ અને ઓસેટ એન્જિનિયર ૨૦૨૬ (૧,૮૦૦ જગ્યાઓ)",
        "organization": "Tata Electronics Private Limited (TEPL)",
        "department": "Dholera Semiconductor Mega Fab & Sanand OSAT Assembly Complex",
        "gov_level": "Private",
        "state": "Gujarat",
        "district": "અમદાવાદ",
        "board_category": "Corporate",
        "vacancies": 1800,
        "qualification": "B.E. / B.Tech / Diploma in Electronics, Mechanical, Electrical, Chemical, or Computer Engineering",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 30,
        "salary_text": "CTC ₹8.0 LPA to ₹15.0 LPA + Subsidized Housing in Dholera Smart City",
        "notification_number": "TATA-SEMI/DHOLERA/2026",
        "apply_url": "https://www.tata.com/careers",
        "official_website": "https://www.tataelectronics.com",
        "selection_process": "Aptitude & Technical Exam -> Physical Cleanroom Suit Assessment -> Technical Interview",
        "syllabus_summary": "Semiconductor Lithography, Etching, Wafer Fabrication, Industrial Automation, Lean Six Sigma",
        "source": "Tata Electronics Official Portal",
        "selection_mode": "interview_assessment",
        "job_category": "gujarat_champions",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Wafer Fab Automation, PLC/SCADA, Cleanroom Class 1/10, Python, Quality Systems",
        "ctc_lpa": 15.0,
        "days_ago": 6,
        "days_ahead": 40
    },
    {
        "title": "AMD India Silicon Design & Software Engineer Trainee 2026 (400 Posts)",
        "title_gu": "એએમડી ઇન્ડિયા (AMD) સિલિકોન ડિઝાઇન અને સોફ્ટવેર એન્જિનિયર ૨૦૨૬ (૪૦૦ જગ્યાઓ)",
        "organization": "AMD India Private Limited (Advanced Micro Devices)",
        "department": "Zen CPU Core Architecture, Radeon GPU & ROCm AI Software",
        "gov_level": "Private",
        "state": "All India",
        "district": "Bengaluru",
        "board_category": "Corporate",
        "vacancies": 400,
        "qualification": "B.E. / B.Tech / M.Tech in ECE / CSE / VLSI / Microelectronics with min 65%",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹18.0 LPA to ₹28.0 LPA + AMD Stock Units",
        "notification_number": "AMD-IN/TECH/2026",
        "apply_url": "https://www.amd.com/en/corporate/careers.html",
        "official_website": "https://www.amd.com",
        "selection_process": "Online Technical Test (Verilog/C/DSA) -> 3 Technical Video Rounds -> HR Round",
        "syllabus_summary": "Digital Electronics, Verilog/SystemVerilog, C/C++, Linux Kernel, GPU Computing (CUDA/ROCm)",
        "source": "AMD Careers Official",
        "selection_mode": "coding_test",
        "job_category": "global_tech",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Verilog, SystemVerilog, C/C++, Linux Kernel, Python, ROCm, Computer Architecture",
        "ctc_lpa": 28.0,
        "days_ago": 11,
        "days_ahead": 35
    },
    {
        "title": "Texas Instruments India Analog & Embedded Processing Systems Trainee 2026 (300 Posts)",
        "title_gu": "ટેક્સાસ ઇન્સ્ટ્રુમેન્ટ્સ ઇન્ડિયા એનાલોગ અને એમ્બેડેડ સિસ્ટમ્સ ટ્રેઇની ૨૦૨૬ (૩૦૦ જગ્યાઓ)",
        "organization": "Texas Instruments India (TI)",
        "department": "Analog Signal Chain, Power Management & MSP/Sitara Microcontrollers",
        "gov_level": "Private",
        "state": "All India",
        "district": "Bengaluru",
        "board_category": "Corporate",
        "vacancies": 300,
        "qualification": "B.E. / B.Tech in ECE / EE / Instrumentation / CSE with strong circuit analysis",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹22.0 LPA to ₹32.0 LPA + Joining Incentive",
        "notification_number": "TI-IN/CAMPUS/2026",
        "apply_url": "https://careers.ti.com",
        "official_website": "https://www.ti.com",
        "selection_process": "TI All-India Technical Test -> Circuit Design Round -> Systems Architecture Round",
        "syllabus_summary": "Analog Circuits, Op-Amps, Digital Logic, Microcontroller Architecture, C/Assembly",
        "source": "Texas Instruments Careers",
        "selection_mode": "coding_test",
        "job_category": "global_tech",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Embedded C, ARM Cortex-M, PCB Design, SPICE Simulation, Python, Verilog",
        "ctc_lpa": 32.0,
        "days_ago": 13,
        "days_ahead": 33
    },

    # -------------------------------------------------------------------------
    # TELECOM & 5G NETWORKS
    # -------------------------------------------------------------------------
    {
        "title": "Bharti Airtel Young Leader & Network Cloud Engineer 2026 (1,400 Posts)",
        "title_gu": "ભારતી એરટેલ યંગ લીડર અને નેટવર્ક ક્લાઉડ એન્જિનિયર ૨૦૨૬ (૧,૪૦૦ જગ્યાઓ)",
        "organization": "Bharti Airtel Limited",
        "department": "Airtel Digital, 5G Core Network, Edge Compute & IoT Operations",
        "gov_level": "Private",
        "state": "All India",
        "district": "All India",
        "board_category": "Corporate",
        "vacancies": 1400,
        "qualification": "B.E. / B.Tech in Electronics / Telecom / CSE / IT or MBA",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹9.0 LPA to ₹16.0 LPA + Airtel Perks",
        "notification_number": "AIRTEL-YL/2026",
        "apply_url": "https://www.airtel.in/careers",
        "official_website": "https://www.airtel.in",
        "selection_process": "Online Cognitive & Domain Test -> Technical Case Round -> Leadership Interview",
        "syllabus_summary": "5G Radio & Core Architecture, TCP/IP, Linux, Cloud Virtualization, Python Automation",
        "source": "Airtel Official Careers",
        "selection_mode": "interview_assessment",
        "job_category": "conglomerate",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "5G Core, OpenRAN, Kubernetes, Linux, Python, Ansible, Wireshark",
        "ctc_lpa": 16.0,
        "days_ago": 10,
        "days_ahead": 35
    },
    {
        "title": "Ericsson India 5G Core Network & Telecom Cloud Trainee 2026 (900 Posts)",
        "title_gu": "એરિક્સન ઇન્ડિયા ૫જી કોર નેટવર્ક અને ક્લાઉડ ટ્રેઇની ૨૦૨૬ (૯૦૦ જગ્યાઓ)",
        "organization": "Ericsson India Global Services",
        "department": "5G RAN R&D, Cloud Native Telecom Infrastructure",
        "gov_level": "Private",
        "state": "All India",
        "district": "Noida",
        "board_category": "Corporate",
        "vacancies": 900,
        "qualification": "B.E. / B.Tech in Electronics & Communication / Computer Science / IT",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹7.0 LPA to ₹12.0 LPA",
        "notification_number": "ERIC-IN/GRAD/2026",
        "apply_url": "https://www.ericsson.com/en/careers",
        "official_website": "https://www.ericsson.com",
        "selection_process": "Online Aptitude & Telecom Exam -> Technical Video Interview -> HR",
        "syllabus_summary": "Telecommunication Fundamentals, 5G NR, IP Routing, C/C++, Linux",
        "source": "Ericsson Careers Portal",
        "selection_mode": "written_exam",
        "job_category": "global_tech",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "5G Protocol Stack, C++, Linux, Docker, Helm, SDN/NFV",
        "ctc_lpa": 12.0,
        "days_ago": 12,
        "days_ahead": 34
    },
    {
        "title": "Nokia Networks India 5G R&D Software Engineer 2026 (750 Posts)",
        "title_gu": "નોકિયા નેટવર્ક્સ ઇન્ડિયા ૫જી આર એન્ડ ડી સોફ્ટવેર એન્જિનિયર ૨૦૨૬ (૭૫૦ જગ્યાઓ)",
        "organization": "Nokia Solutions and Networks India Private Limited",
        "department": "Mobile Networks R&D, 5G Core & Network Slicing Labs",
        "gov_level": "Private",
        "state": "All India",
        "district": "Bengaluru",
        "board_category": "Corporate",
        "vacancies": 750,
        "qualification": "B.E. / B.Tech in CSE / ECE / IT with good software development skills",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹8.0 LPA to ₹14.0 LPA",
        "notification_number": "NOKIA-RD/IND/2026",
        "apply_url": "https://www.nokia.com/about-us/careers",
        "official_website": "https://www.nokia.com",
        "selection_process": "Online Coding Challenge -> Technical Architecture Interview -> Manager Round",
        "syllabus_summary": "Data Structures, Modern C++, Linux Multi-threading, Network Protocols",
        "source": "Nokia Careers Official",
        "selection_mode": "coding_test",
        "job_category": "global_tech",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "C++, Linux, 5G NR Protocols, Git, Jenkins, Docker, Python",
        "ctc_lpa": 14.0,
        "days_ago": 14,
        "days_ahead": 36
    },

    # -------------------------------------------------------------------------
    # AVIATION & AIRLINES
    # -------------------------------------------------------------------------
    {
        "title": "IndiGo Airlines Aircraft Maintenance & Flight Operations Trainee 2026 (1,100 Posts)",
        "title_gu": "ઇન્ડિગો એરલાઇન્સ એરક્રાફ્ટ મેન્ટેનન્સ અને ફ્લાઇટ ઓપરેશન્સ ટ્રેઇની ૨૦૨૬ (૧,૧૦૦ જગ્યાઓ)",
        "organization": "InterGlobe Aviation Limited (IndiGo)",
        "department": "Engineering & Maintenance, Flight Operations & Ground Aviation Tech",
        "gov_level": "Private",
        "state": "All India",
        "district": "અમદાવાદ",
        "board_category": "Corporate",
        "vacancies": 1100,
        "qualification": "B.E. / B.Tech in Aeronautical / Aerospace / Mechanical / Electrical / Electronics / CSE or AME License",
        "qualification_level": "Engineering",
        "age_min": 18,
        "age_max": 27,
        "salary_text": "CTC ₹5.5 LPA to ₹10.5 LPA + Staff Airline Travel Privileges",
        "notification_number": "INDIGO-ENGG/2026/02",
        "apply_url": "https://careers.goindigo.in",
        "official_website": "https://www.goindigo.in",
        "selection_process": "Aviation Aptitude Assessment -> Technical Interview -> Medical Fitness Exam",
        "syllabus_summary": "Aerodynamics, Aircraft Electrical Systems, DGCA CAR Regulations, Basic Avionics",
        "source": "IndiGo Official Careers",
        "selection_mode": "interview_assessment",
        "job_category": "conglomerate",
        "is_btech_cse": 0,
        "experience_level": "fresher",
        "tech_stack": "Airbus A320 Avionics, Flight Telemetry, Predictive Maintenance, Aviation ERP",
        "ctc_lpa": 10.5,
        "days_ago": 9,
        "days_ahead": 30
    },
    {
        "title": "Air India (Tata Group) Aviation Engineering & Digital Operations Trainee 2026 (1,300 Posts)",
        "title_gu": "એર ઇન્ડિયા (ટાટા ગ્રુપ) એવિએશન એન્જિનિયરિંગ અને ડિજિટલ ઓપરેશન્સ ૨૦૨૬ (૧,૩૦૦ જગ્યાઓ)",
        "organization": "Air India Limited (Tata Sons Enterprise)",
        "department": "Fleet Engineering, Flight Dispatch & Digital Transformation Unit",
        "gov_level": "Private",
        "state": "All India",
        "district": "All India",
        "board_category": "Corporate",
        "vacancies": 1300,
        "qualification": "B.Tech / B.E. in Any Engineering stream OR Any Graduate",
        "qualification_level": "Engineering",
        "age_min": 18,
        "age_max": 28,
        "salary_text": "CTC ₹6.5 LPA to ₹12.0 LPA + Flying Benefits",
        "notification_number": "AI-TATA/AVN/2026",
        "apply_url": "https://www.airindia.com/careers.html",
        "official_website": "https://www.airindia.com",
        "selection_process": "Online Written Aptitude Test -> Technical Interview -> Personal Interview",
        "syllabus_summary": "General Aptitude, Aviation Basics, Aircraft Safety, Customer Experience Standards",
        "source": "Air India Official",
        "selection_mode": "written_exam",
        "job_category": "conglomerate",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Airline Operations, Safety Management Systems, Flight Scheduling, Aviation Software",
        "ctc_lpa": 12.0,
        "days_ago": 11,
        "days_ahead": 32
    },
    {
        "title": "MakeMyTrip India Software Development Engineer (SDE-1 Travel Tech) 2026 (350 Posts)",
        "title_gu": "મેકમાયટ્રિપ ઇન્ડિયા સોફ્ટવેર ડેવલપમેન્ટ એન્જિનિયર (SDE-1) ૨૦૨૬ (૩૫૦ જગ્યાઓ)",
        "organization": "MakeMyTrip India Private Limited",
        "department": "Hotels & Flights Booking Engine, Dynamic Pricing & Recommendation AI",
        "gov_level": "Private",
        "state": "All India",
        "district": "Gurugram",
        "board_category": "Corporate",
        "vacancies": 350,
        "qualification": "B.E. / B.Tech in CSE / IT / Software Engineering or MCA",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹16.0 LPA to ₹25.0 LPA + Travel Allowances",
        "notification_number": "MMT-TECH/SDE1/2026",
        "apply_url": "https://careers.makemytrip.com",
        "official_website": "https://www.makemytrip.com",
        "selection_process": "Online Coding Assessment -> Machine Coding -> 2 Tech Rounds -> HR",
        "syllabus_summary": "DSA, Low Level Design, High Throughput Distributed Systems, Microservices",
        "source": "MakeMyTrip Careers Portal",
        "selection_mode": "coding_test",
        "job_category": "unicorns",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Java, Python, Spring Boot, Redis, Kafka, Elasticsearch, AWS, React",
        "ctc_lpa": 25.0,
        "days_ago": 7,
        "days_ahead": 28
    },

    # -------------------------------------------------------------------------
    # GLOBAL RETAIL & ENTERPRISE GCCs
    # -------------------------------------------------------------------------
    {
        "title": "Walmart Global Tech India Software Engineer Trainee 2026 (950 Posts)",
        "title_gu": "વોલમાર્ટ ગ્લોબલ ટેક ઇન્ડિયા સોફ્ટવેર એન્જિનિયર ટ્રેઇની ૨૦૨૬ (૯૫૦ જગ્યાઓ)",
        "organization": "Walmart Global Tech India",
        "department": "Global Supply Chain Tech, Omnichannel Retail & Merchant Platforms",
        "gov_level": "Private",
        "state": "All India",
        "district": "Bengaluru",
        "board_category": "Corporate",
        "vacancies": 950,
        "qualification": "B.E. / B.Tech in CSE / IT / ECE with min 65% or 7.0 CGPA",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹20.0 LPA to ₹32.0 LPA + Annual Performance Grant",
        "notification_number": "WMT-TECH/IND/2026",
        "apply_url": "https://careers.walmart.com",
        "official_website": "https://tech.walmart.com",
        "selection_process": "Walmart CodeHers / Campus Coding Test -> 2 Technical Rounds -> Hiring Manager",
        "syllabus_summary": "Data Structures, Algorithms, Distributed Caching, High Scale Microservices, Java/Go",
        "source": "Walmart Global Tech Official",
        "selection_mode": "coding_test",
        "job_category": "global_tech",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Java, Golang, Kafka, Cassandra, Kubernetes, Azure, React",
        "ctc_lpa": 32.0,
        "days_ago": 6,
        "days_ahead": 35
    },
    {
        "title": "Target India Technology Engineer Trainee 2026 (450 Posts)",
        "title_gu": "ટાર્ગેટ ઇન્ડિયા ટેકનોલોજી એન્જિનિયર ટ્રેઇની ૨૦૨૬ (૪૫૦ જગ્યાઓ)",
        "organization": "Target Corporation India Private Limited",
        "department": "Retail Automation, Supply Chain Engineering & Cloud Platform",
        "gov_level": "Private",
        "state": "All India",
        "district": "Bengaluru",
        "board_category": "Corporate",
        "vacancies": 450,
        "qualification": "B.E. / B.Tech in Computer Science / IT / Circuit branches",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹15.0 LPA to ₹24.0 LPA",
        "notification_number": "TARGET-IND/2026",
        "apply_url": "https://india.target.com/careers",
        "official_website": "https://corporate.target.com",
        "selection_process": "Coding Assessment -> Technical Video Round -> Culture & Values Round",
        "syllabus_summary": "DSA, Object Oriented Design, System Basics, Clean Code",
        "source": "Target India Careers",
        "selection_mode": "coding_test",
        "job_category": "global_tech",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Java, Kotlin, Python, GCP, Spinnaker, Kafka, React",
        "ctc_lpa": 24.0,
        "days_ago": 12,
        "days_ahead": 30
    }
]
