"""
Additional 42 Major Private Employers in India
"""
EXTRA_COMPANIES = [
    # --- Previously Key Companies (Amazon, Flipkart, Google, PhonePe, Paytm, Zerodha, Crest, Radixweb, GIFT City) ---
    {
        "title": "Amazon India Software Development Engineer (SDE-1 & AWS Associate) 2026 (2,500 Posts)",
        "title_gu": "એમેઝોન ઇન્ડિયા સોફ્ટવેર ડેવલપમેન્ટ એન્જિનિયર (SDE-1) ૨૦૨૬ (૨,૫૦૦ જગ્યાઓ)",
        "organization": "Amazon Development Centre India / AWS Cloud Services",
        "department": "AWS Cloud Computing, Retail E-Commerce Systems & Alexa AI",
        "gov_level": "Private",
        "state": "All India",
        "district": "All India",
        "board_category": "Corporate",
        "vacancies": 2500,
        "qualification": "B.E. / B.Tech in CSE / IT / ECE or MCA with strong data structures knowledge",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹18.0 LPA to ₹34.0 LPA (Base + Sign-on Bonus + RSU Stock)",
        "notification_number": "AMZ-IN/SDE1/2026",
        "apply_url": "https://www.amazon.jobs",
        "official_website": "https://www.amazon.in",
        "selection_process": "Online Coding Assessment (2 questions + Work Style Simulation) -> 3 Technical Video Rounds -> Bar Raiser",
        "syllabus_summary": "Data Structures, Algorithms, System Architecture, Amazon 16 Leadership Principles, Java/C++",
        "source": "Amazon Jobs Official Portal",
        "selection_mode": "coding_test",
        "job_category": "global_tech",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Java, Python, C++, AWS Services, Distributed Storage, DynamoDB, Microservices",
        "ctc_lpa": 34.0,
        "days_ago": 15,
        "days_ahead": 35
    },
    {
        "title": "Flipkart Software Development Engineer (SDE-1 & Supply Chain Tech) 2026 (1,200 Posts)",
        "title_gu": "ફ્લિપકાર્ટ સોફ્ટવેર ડેવલપમેન્ટ એન્જિનિયર (SDE-1 & સપ્લાય ચેઇન) ૨૦૨૬ (૧,૨૦૦ જગ્યાઓ)",
        "organization": "Flipkart Internet Private Limited (Walmart Group)",
        "department": "E-Commerce Marketplace, Supply Chain Robotics & Big Billion Days Tech",
        "gov_level": "Private",
        "state": "All India",
        "district": "All India",
        "board_category": "Corporate",
        "vacancies": 1200,
        "qualification": "B.E. / B.Tech in Computer Science / IT / Software Engineering or MCA",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹16.0 LPA to ₹28.0 LPA + ESOPs + Annual Bonus",
        "notification_number": "FLIP-TECH/SDE1/2026",
        "apply_url": "https://www.flipkartcareers.com",
        "official_website": "https://www.flipkart.com",
        "selection_process": "Coding Assessment (GRIP Hackathon) -> Machine Coding Round -> Data Structures & Algorithms -> HR",
        "syllabus_summary": "Object Oriented Design, Low Level System Design, Clean Code, Data Structures, Concurrency",
        "source": "Flipkart Careers Portal",
        "selection_mode": "coding_test",
        "job_category": "global_tech",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Java, Kotlin, MySQL, Redis, Kafka, Distributed Caching, Dropwizard, React",
        "ctc_lpa": 28.0,
        "days_ago": 12,
        "days_ahead": 30
    },
    {
        "title": "Google India Associate Software Engineer & Cloud Technical Resident 2026 (450 Posts)",
        "title_gu": "ગૂગલ ઇન્ડિયા (Google India) એસોસિએટ સોફ્ટવેર એન્જિનિયર ૨૦૨૬ (૪૫૦ જગ્યાઓ)",
        "organization": "Google India Pvt Ltd / Alphabet Inc.",
        "department": "Google Cloud, Android OS, Search Infrastructure & Payments Ecosystem",
        "gov_level": "Private",
        "state": "All India",
        "district": "All India",
        "board_category": "Corporate",
        "vacancies": 450,
        "qualification": "B.E. / B.Tech in CSE / IT / Mathematics and Computing or related technical fields",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 28,
        "salary_text": "CTC ₹22.0 LPA to ₹42.0 LPA (Base + Google Equity Grants + Sign-on)",
        "notification_number": "GOOG-IN/SWE-UNIV/26",
        "apply_url": "https://careers.google.com",
        "official_website": "https://www.google.com",
        "selection_process": "Google Online Challenge (GOC) -> 3 Technical Coding Interviews -> Googleyness Round",
        "syllabus_summary": "Graph Theory, Dynamic Programming, Complexity Analysis, High Performance C++/Java/Python",
        "source": "Google Careers Official",
        "selection_mode": "coding_test",
        "job_category": "global_tech",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "C++, Java, Python, Go, GCP, Spanner, Kubernetes, TensorFlow",
        "ctc_lpa": 42.0,
        "days_ago": 14,
        "days_ahead": 28
    },
    {
        "title": "PhonePe Software Engineer - High Concurrency Payments Infrastructure 2026 (350 Posts)",
        "title_gu": "ફોનપે (PhonePe) સોફ્ટવેર એન્જિનિયર - હાઇ કોનકરન્સી પેમેન્ટ્સ ઇન્ફ્રાસ્ટ્રક્ચર ૨૦૨૬ (૩૫૦ જગ્યાઓ)",
        "organization": "PhonePe Private Limited",
        "department": "UPI Switch Core, Merchant Payments Gateway & Financial Services",
        "gov_level": "Private",
        "state": "All India",
        "district": "All India",
        "board_category": "Corporate",
        "vacancies": 350,
        "qualification": "B.E. / B.Tech in CSE / IT with high proficiency in algorithms and distributed systems",
        "qualification_level": "Engineering",
        "age_min": 21,
        "age_max": 29,
        "salary_text": "CTC ₹16.0 LPA to ₹26.0 LPA + PhonePe ESOPs",
        "notification_number": "PHONEPE/SWE-PAY/2026",
        "apply_url": "https://www.phonepe.com/careers",
        "official_website": "https://www.phonepe.com",
        "selection_process": "Online Coding Assessment -> Machine Coding Round -> Problem Solving & System Architecture -> HR",
        "syllabus_summary": "Low Level System Design, Concurrent Programming, Kafka, NoSQL Databases, Microservices",
        "source": "PhonePe Careers Official",
        "selection_mode": "coding_test",
        "job_category": "unicorns",
        "is_btech_cse": 1,
        "experience_level": "all",
        "tech_stack": "Java, Dropwizard, Kafka, Aerospike, HBase, Docker, High Throughput Architecture",
        "ctc_lpa": 26.0,
        "days_ago": 8,
        "days_ahead": 32
    },
    {
        "title": "Paytm / One97 Communications Backend & UPI Integrations Engineer 2026 (300 Posts)",
        "title_gu": "પેટીએમ (Paytm) બેકએન્ડ અને UPI ઇન્ટિગ્રેશન એન્જિનિયર ૨૦૨૬ (૩૦૦ જગ્યાઓ)",
        "organization": "One97 Communications Limited (Paytm)",
        "department": "Paytm Payments Gateway, Soundbox IoT & Merchant QR Platform",
        "gov_level": "Private",
        "state": "All India",
        "district": "All India",
        "board_category": "Corporate",
        "vacancies": 300,
        "qualification": "B.E. / B.Tech in Computer Science / IT / Electronics or MCA",
        "qualification_level": "Engineering",
        "age_min": 21,
        "age_max": 29,
        "salary_text": "CTC ₹10.0 LPA to ₹16.0 LPA + Performance Incentives",
        "notification_number": "PAYTM/BACKEND-UPI/2026",
        "apply_url": "https://careers.paytm.com",
        "official_website": "https://paytm.com",
        "selection_process": "Online Coding Test -> Technical Interview 1 (DSA) -> Technical Interview 2 (Systems) -> HR",
        "syllabus_summary": "Java, Spring Boot, MySQL, Redis, REST APIs, Microservices, Security Protocols",
        "source": "Paytm Careers Official",
        "selection_mode": "coding_test",
        "job_category": "unicorns",
        "is_btech_cse": 1,
        "experience_level": "all",
        "tech_stack": "Java, Spring Boot, Node.js, Redis, Kafka, MySQL, AWS",
        "ctc_lpa": 16.0,
        "days_ago": 11,
        "days_ahead": 29
    },
    {
        "title": "Zerodha Broking Junior Python Engineer & Trading Tech Analyst 2026 (80 Posts)",
        "title_gu": "ઝેરોધા (Zerodha) જુનિયર પાયથોન એન્જિનિયર & ટ્રેડિંગ ટેક એનાલિસ્ટ ૨૦૨૬ (૮૦ જગ્યાઓ)",
        "organization": "Zerodha Broking Limited",
        "department": "Kite Trading Platform, Ultra-Low Latency Order Routing & Risk Systems",
        "gov_level": "Private",
        "state": "All India",
        "district": "All India",
        "board_category": "Corporate",
        "vacancies": 80,
        "qualification": "B.E. / B.Tech / B.Sc in CS / Mathematics with strong FOSS & open-source contributions",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 29,
        "salary_text": "CTC ₹10.0 LPA to ₹14.0 LPA + 100% Health & Profit Share",
        "notification_number": "ZERODHA/TECH/2026/01",
        "apply_url": "https://zerodha.com/careers",
        "official_website": "https://zerodha.com",
        "selection_process": "FOSS Code Review & Coding Assignment -> Technical Conversation with Senior Engineers -> Offer",
        "syllabus_summary": "Python internals, PostgreSQL optimization, Linux systems, WebSockets, Go programming",
        "source": "Zerodha Careers Portal",
        "selection_mode": "interview_assessment",
        "job_category": "unicorns",
        "is_btech_cse": 1,
        "experience_level": "all",
        "tech_stack": "Python, Golang, PostgreSQL, Redis, Vue.js, Linux, NGINX, HAProxy",
        "ctc_lpa": 14.0,
        "days_ago": 9,
        "days_ahead": 31
    },
    {
        "title": "Crest Data Systems (Ahmedabad) Cloud & Cyber Security Engineer 2026 (250 Posts)",
        "title_gu": "ક્રેસ્ટ ડેટા સિસ્ટમ્સ (અમદાવાદ) ક્લાઉડ & સાયબર સિક્યોરિટી એન્જિનિયર ૨૦૨૬ (૨૫૦ જગ્યાઓ)",
        "organization": "Crest Data Systems (Ahmedabad HQ)",
        "department": "Data Analytics, Enterprise Cloud Automation & Splunk/Datadog Integrations",
        "gov_level": "Private",
        "state": "Gujarat",
        "district": "અમદાવાદ",
        "board_category": "Corporate",
        "vacancies": 250,
        "qualification": "B.E. / B.Tech in CSE / IT with min 65% marks",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 27,
        "salary_text": "CTC ₹6.0 LPA to ₹9.0 LPA + Professional Certification Sponsorship",
        "notification_number": "CREST/AMD/TECH/2026",
        "apply_url": "https://www.crestdatasys.com/careers",
        "official_website": "https://www.crestdatasys.com",
        "selection_process": "Online Coding & Aptitude Test -> Technical Interview -> HR Discussion",
        "syllabus_summary": "Python Programming, Linux Commands, Networking Protocols, Cloud Fundamentals, Data Structures",
        "source": "Crest Data Careers Portal",
        "selection_mode": "coding_test",
        "job_category": "gujarat_champions",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Python, Go, AWS, Docker, Splunk, Elastic, DevOps, Linux",
        "ctc_lpa": 9.0,
        "days_ago": 13,
        "days_ahead": 27
    },
    {
        "title": "Radixweb (Ahmedabad) Full Stack Web & Mobile App Developer 2026 (200 Posts)",
        "title_gu": "રેડિક્સવેબ (અમદાવાદ) ફુલ સ્ટેક વેબ & મોબાઇલ એપ ડેવલપર ૨૦૨૬ (૨૦૦ જગ્યાઓ)",
        "organization": "Radixweb / Ekyam Software Park",
        "department": "Custom Enterprise Software, Cloud Application Development & SaaS",
        "gov_level": "Private",
        "state": "Gujarat",
        "district": "અમદાવાદ",
        "board_category": "Corporate",
        "vacancies": 200,
        "qualification": "B.E. / B.Tech in CSE / IT or MCA with min 60% marks",
        "qualification_level": "Engineering",
        "age_min": 21,
        "age_max": 28,
        "salary_text": "CTC ₹5.0 LPA to ₹7.5 LPA + Performance Incentives",
        "notification_number": "RADIX/EKYAM/2026",
        "apply_url": "https://radixweb.com/careers",
        "official_website": "https://radixweb.com",
        "selection_process": "Technical Aptitude & Coding Assessment -> Technical Interview -> Management Round",
        "syllabus_summary": "JavaScript/TypeScript, React or Angular, Node.js or .NET Core, SQL Database Design",
        "source": "Radixweb Careers Portal",
        "selection_mode": "interview_assessment",
        "job_category": "gujarat_champions",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "React, Node.js, .NET Core, Angular, MongoDB, Azure, Flutter",
        "ctc_lpa": 7.5,
        "days_ago": 10,
        "days_ahead": 30
    },
    {
        "title": "GIFT City FinTech Companies Software Developer & Blockchain Engineer 2026 (450 Posts)",
        "title_gu": "ગિફ્ટ સિટી (GIFT City ગાંધીનગર) ફિનટેક કંપનીઓમાં સોફ્ટવેર ડેવલપર ૨૦૨૬ (૪૫૦ જગ્યાઓ)",
        "organization": "GIFT City FinTech Consortium (Global Financial Tech Hub)",
        "department": "International Financial Services Centre (IFSC) Banking & Trading Tech",
        "gov_level": "Private",
        "state": "Gujarat",
        "district": "ગાંધીનગર",
        "board_category": "Corporate",
        "vacancies": 450,
        "qualification": "B.E. / B.Tech in CSE / IT / Electronics or MCA with min 60% aggregate",
        "qualification_level": "Engineering",
        "age_min": 21,
        "age_max": 32,
        "salary_text": "₹60,000/- to ₹1,40,000/- Month (CTC ₹7.2 to ₹16.0 LPA)",
        "notification_number": "GIFT/FINTECH/2026/01",
        "apply_url": "https://www.giftgujarat.in/careers",
        "official_website": "https://www.giftgujarat.in",
        "selection_process": "Online Coding Assessment -> Technical Interview Round -> IFSC Regulatory Screening",
        "syllabus_summary": "Data Structures, Algorithms, Cryptography, Blockchain, Smart Contracts, Banking APIs, Go/Python",
        "source": "GIFT City Official Recruitment Portal",
        "selection_mode": "coding_test",
        "job_category": "gujarat_champions",
        "is_btech_cse": 1,
        "experience_level": "all",
        "tech_stack": "Python, Golang, Solidity, React, Kafka, Docker, Kubernetes, PostgreSQL",
        "ctc_lpa": 16.0,
        "days_ago": 15,
        "days_ahead": 25
    },

    # --- Additional IT Services & Global Integrators ---
    {
        "title": "Mphasis Associate Software Engineer & Cloud Architecture Trainee 2026 (4,500 Posts)",
        "title_gu": "એમ્ફાસિસ (Mphasis) એસોસિએટ સોફ્ટવેર એન્જિનિયર ૨૦૨૬ (૪,૫૦૦ જગ્યાઓ)",
        "organization": "Mphasis Limited (Blackstone Portfolio)",
        "department": "Next-Gen Banking & Financial Services Architecture",
        "gov_level": "Private",
        "state": "All India",
        "district": "Bengaluru",
        "board_category": "Corporate",
        "vacancies": 4500,
        "qualification": "B.E. / B.Tech in CSE / IT / ECE / EEE or MCA with min 60%",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 26,
        "salary_text": "CTC ₹4.0 LPA to ₹5.5 LPA",
        "notification_number": "MPHASIS/CAMPUS/2026",
        "apply_url": "https://careers.mphasis.com",
        "official_website": "https://www.mphasis.com",
        "selection_process": "Online Aptitude & Coding Round -> Technical Interview -> HR",
        "syllabus_summary": "Core Java, OOPs, Data Structures, Basic SQL, Web Technologies",
        "source": "Mphasis Careers Official",
        "selection_mode": "coding_test",
        "job_category": "it_services",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Java, Python, AWS Cloud, SQL, Spring Boot",
        "ctc_lpa": 5.5,
        "days_ago": 12,
        "days_ahead": 28
    },
    {
        "title": "Coforge Associate Software Engineer & Digital Solutions Trainee 2026 (2,500 Posts)",
        "title_gu": "કોફોર્જ (Coforge) એસોસિએટ સોફ્ટવેર એન્જિનિયર ૨૦૨૬ (૨,૫૦૦ જગ્યાઓ)",
        "organization": "Coforge Limited",
        "department": "Aviation, Insurance & Public Sector Digital Systems",
        "gov_level": "Private",
        "state": "All India",
        "district": "Greater Noida",
        "board_category": "Corporate",
        "vacancies": 2500,
        "qualification": "B.E. / B.Tech in any branch with min 60% marks",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 26,
        "salary_text": "CTC ₹4.2 LPA to ₹6.0 LPA",
        "notification_number": "COFORGE/ASE/2026",
        "apply_url": "https://www.coforge.com/careers",
        "official_website": "https://www.coforge.com",
        "selection_process": "Aptitude + Technical MCQ -> Coding Test -> Technical Interview",
        "syllabus_summary": "Logical Reasoning, Quantitative Analysis, Programming in Java/C#, RDBMS",
        "source": "Coforge Careers Official",
        "selection_mode": "coding_test",
        "job_category": "it_services",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Java, .NET, Cloud, SQL, Angular, DevOps",
        "ctc_lpa": 6.0,
        "days_ago": 10,
        "days_ahead": 30
    },
    {
        "title": "Birlasoft Associate Consultant & Software Developer 2026 (2,000 Posts)",
        "title_gu": "બિરલાસોફ્ટ (Birlasoft) એસોસિએટ કન્સલ્ટન્ટ ૨૦૨૬ (૨,૦૦૦ જગ્યાઓ)",
        "organization": "Birlasoft Limited (CK Birla Group)",
        "department": "Manufacturing, Life Sciences & BFSI Digital Services",
        "gov_level": "Private",
        "state": "All India",
        "district": "Pune",
        "board_category": "Corporate",
        "vacancies": 2000,
        "qualification": "B.E. / B.Tech / MCA with min 60%",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 26,
        "salary_text": "CTC ₹4.0 LPA to ₹5.5 LPA",
        "notification_number": "BSOFT/CAMPUS/2026",
        "apply_url": "https://www.birlasoft.com/careers",
        "official_website": "https://www.birlasoft.com",
        "selection_process": "Online Assessment -> Technical Interview -> HR",
        "syllabus_summary": "Aptitude, Core Java, Cloud, Data Structures",
        "source": "Birlasoft Careers Official",
        "selection_mode": "coding_test",
        "job_category": "it_services",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Java, Python, Oracle, SAP, Azure",
        "ctc_lpa": 5.5,
        "days_ago": 11,
        "days_ahead": 29
    },
    {
        "title": "Zensar Technologies Junior Software Engineer Trainee 2026 (1,800 Posts)",
        "title_gu": "ઝેનસાર ટેક્નોલોજીસ (Zensar) જુનિયર સોફ્ટવેર એન્જિનિયર ૨૦૨૬ (૧,૮૦૦ જગ્યાઓ)",
        "organization": "Zensar Technologies Limited (RPG Group)",
        "department": "Enterprise Experience & Technology Services",
        "gov_level": "Private",
        "state": "All India",
        "district": "Pune",
        "board_category": "Corporate",
        "vacancies": 1800,
        "qualification": "B.E. / B.Tech in CSE / IT / ECE with min 60%",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 26,
        "salary_text": "CTC ₹4.0 LPA to ₹5.0 LPA",
        "notification_number": "ZENSAR/CAMPUS-26",
        "apply_url": "https://www.zensar.com/careers",
        "official_website": "https://www.zensar.com",
        "selection_process": "Cognitive Aptitude -> Coding Challenge -> Technical Round",
        "syllabus_summary": "Analytical Skills, Problem Solving, Java/Python Basics",
        "source": "Zensar Official",
        "selection_mode": "coding_test",
        "job_category": "it_services",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Java, Full Stack, React, Cloud, SQL",
        "ctc_lpa": 5.0,
        "days_ago": 9,
        "days_ahead": 31
    },
    {
        "title": "KPIT Technologies Automotive Embedded Software Trainee 2026 (2,200 Posts)",
        "title_gu": "કેપીઆઈટી (KPIT) ઓટોમોટિવ એમ્બેડેડ સોફ્ટવેર ટ્રેઇની ૨૦૨૬ (૨,૨૦૦ જગ્યાઓ)",
        "organization": "KPIT Technologies Limited",
        "department": "Autonomous Driving, EV Powertrain Software & AUTOSAR",
        "gov_level": "Private",
        "state": "All India",
        "district": "Pune",
        "board_category": "Corporate",
        "vacancies": 2200,
        "qualification": "B.E. / B.Tech in ECE / EE / Instrumentation / CSE / Mechatronics with min 60%",
        "qualification_level": "Engineering",
        "age_min": 20,
        "age_max": 27,
        "salary_text": "CTC ₹4.5 LPA to ₹6.5 LPA",
        "notification_number": "KPIT/AUTOSAR/2026",
        "apply_url": "https://www.kpit.com/careers",
        "official_website": "https://www.kpit.com",
        "selection_process": "Online Technical Assessment -> Embedded C Interview -> HR",
        "syllabus_summary": "Embedded C, Microcontrollers, Microprocessors, Basic Electronics, C++",
        "source": "KPIT Careers Official",
        "selection_mode": "coding_test",
        "job_category": "it_services",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Embedded C, AUTOSAR, CAN Bus, RTOS, MATLAB/Simulink, Python",
        "ctc_lpa": 6.5,
        "days_ago": 13,
        "days_ahead": 27
    },

    # --- Additional Private BFSI ---
    {
        "title": "IndusInd Bank Associate Manager & FinTech Solutions Trainee 2026 (1,500 Posts)",
        "title_gu": "ઇન્ડસઇન્ડ બેન્ક એસોસિએટ મેનેજર & ફિનટેક સોલ્યુશન્સ ૨૦૨૬ (૧,૫૦૦ જગ્યાઓ)",
        "organization": "IndusInd Bank Limited",
        "department": "Consumer Banking, Vehicle Finance & Digital Payments",
        "gov_level": "Private",
        "state": "All India",
        "district": "Mumbai",
        "board_category": "Corporate",
        "vacancies": 1500,
        "qualification": "Graduation in any discipline or MBA/B.Tech with min 50%",
        "qualification_level": "Graduate",
        "age_min": 21,
        "age_max": 29,
        "salary_text": "CTC ₹4.5 LPA to ₹7.0 LPA",
        "notification_number": "INDUSIND/AM/2026",
        "apply_url": "https://www.indusind.com/in/en/personal/careers.html",
        "official_website": "https://www.indusind.com",
        "selection_process": "Aptitude Exam -> Panel Interview",
        "syllabus_summary": "Banking Acumen, Numerical Reasoning, Customer Service",
        "source": "IndusInd Careers Official",
        "selection_mode": "written_exam",
        "job_category": "bfsi",
        "is_btech_cse": 1,
        "experience_level": "all",
        "tech_stack": "Core Banking, CRM, Financial Analysis, Python",
        "ctc_lpa": 7.0,
        "days_ago": 12,
        "days_ahead": 28
    },
    {
        "title": "Tata Capital Financial Analyst & Retail Lending Trainee 2026 (800 Posts)",
        "title_gu": "ટાટા કેપિટલ ફાઇનાન્શિયલ એનાલિસ્ટ અને રિટેલ લેન્ડિંગ ટ્રેઇની ૨૦૨૬ (૮૦૦ જગ્યાઓ)",
        "organization": "Tata Capital Limited (Tata Group)",
        "department": "Consumer Finance, Commercial Lending & Wealth Services",
        "gov_level": "Private",
        "state": "All India",
        "district": "Mumbai",
        "board_category": "Corporate",
        "vacancies": 800,
        "qualification": "Any Graduate (B.Com, B.Tech, BBA, B.Sc) or MBA with min 55%",
        "qualification_level": "Graduate",
        "age_min": 21,
        "age_max": 28,
        "salary_text": "CTC ₹5.0 LPA to ₹7.5 LPA",
        "notification_number": "TATACAP/RET-LEND/2026",
        "apply_url": "https://www.tatacapital.com/careers.html",
        "official_website": "https://www.tatacapital.com",
        "selection_process": "Online Aptitude Round -> Personal Interview",
        "syllabus_summary": "Financial Analysis, Credit Appraisal, Logical Reasoning",
        "source": "Tata Capital Official",
        "selection_mode": "written_exam",
        "job_category": "bfsi",
        "is_btech_cse": 1,
        "experience_level": "all",
        "tech_stack": "Financial Modeling, Advanced Excel, Risk Analytics",
        "ctc_lpa": 7.5,
        "days_ago": 10,
        "days_ahead": 30
    },
    {
        "title": "Aditya Birla Capital Associate Management Trainee 2026 (650 Posts)",
        "title_gu": "આદિત્ય બિરલા કેપિટલ એસોસિએટ મેનેજમેન્ટ ટ્રેઇની ૨૦૨૬ (૬૫૦ જગ્યાઓ)",
        "organization": "Aditya Birla Capital Limited (ABCL)",
        "department": "Life Insurance, Asset Management & Housing Finance",
        "gov_level": "Private",
        "state": "All India",
        "district": "Mumbai",
        "board_category": "Corporate",
        "vacancies": 650,
        "qualification": "Graduate in any stream or MBA with min 55%",
        "qualification_level": "Graduate",
        "age_min": 21,
        "age_max": 29,
        "salary_text": "CTC ₹5.0 LPA to ₹7.2 LPA",
        "notification_number": "ABCL/AMT/2026",
        "apply_url": "https://www.adityabirlacapital.com/careers",
        "official_website": "https://www.adityabirlacapital.com",
        "selection_process": "Online Test -> Group Discussion -> Interview",
        "syllabus_summary": "Financial Products, Logical Reasoning, Verbal Communication",
        "source": "Aditya Birla Capital Official",
        "selection_mode": "written_exam",
        "job_category": "bfsi",
        "is_btech_cse": 1,
        "experience_level": "all",
        "tech_stack": "FinTech Tools, CRM, Analytics, Excel",
        "ctc_lpa": 7.2,
        "days_ago": 8,
        "days_ahead": 32
    },
    {
        "title": "Muthoot Finance Branch Operations Executive & Probationary Officer 2026 (1,200 Posts)",
        "title_gu": "મુથૂટ ફાઇનાન્સ બ્રાન્ચ ઓપરેશન્સ એક્ઝિક્યુટિવ & PO ૨૦૨૬ (૧,૨૦૦ જગ્યાઓ)",
        "organization": "Muthoot Finance Limited",
        "department": "Gold Loans, Foreign Exchange & Microfinance Operations",
        "gov_level": "Private",
        "state": "Gujarat",
        "district": "અમદાવાદ",
        "board_category": "Corporate",
        "vacancies": 1200,
        "qualification": "Graduation in any discipline (B.Com, B.A, B.Sc, B.Tech)",
        "qualification_level": "Graduate",
        "age_min": 20,
        "age_max": 30,
        "salary_text": "CTC ₹3.8 LPA to ₹5.0 LPA + Incentives",
        "notification_number": "MUTHOOT/BOE-PO/2026",
        "apply_url": "https://www.muthootfinance.com/careers",
        "official_website": "https://www.muthootfinance.com",
        "selection_process": "Walk-In Interview -> Aptitude Assessment -> Verification",
        "syllabus_summary": "General Knowledge, Basic Math, Cash Management",
        "source": "Muthoot Finance Official",
        "selection_mode": "walk_in",
        "job_category": "bfsi",
        "is_btech_cse": 1,
        "experience_level": "all",
        "tech_stack": "Core Lending Software, Cash Verification, Excel",
        "ctc_lpa": 5.0,
        "days_ago": 14,
        "days_ahead": 26
    },

    # --- Additional Heavy Industry & Conglomerates ---
    {
        "title": "Titan Company Graduate Trainee (Design, Retail Tech & Watch Division) 2026 (300 Posts)",
        "title_gu": "ટાઇટન કંપની (Titan Tata) ગ્રેજ્યુએટ ટ્રેઇની ૨૦૨૬ (૩૦૦ જગ્યાઓ)",
        "organization": "Titan Company Limited (Tata Group)",
        "department": "Watches, Tanishq Jewellery Manufacturing & Smart Wearables",
        "gov_level": "Private",
        "state": "All India",
        "district": "Bengaluru",
        "board_category": "Corporate",
        "vacancies": 300,
        "qualification": "B.E. / B.Tech in Mechanical / Production / CSE or Design Graduate",
        "qualification_level": "Engineering",
        "age_min": 21,
        "age_max": 27,
        "salary_text": "CTC ₹5.5 LPA to ₹7.5 LPA",
        "notification_number": "TITAN/GRAD-TR/2026",
        "apply_url": "https://www.titancompany.in/careers",
        "official_website": "https://www.titancompany.in",
        "selection_process": "Online Assessment -> Design & Technical Interview -> HR",
        "syllabus_summary": "Precision Engineering, Micro-Mechanics, Product Design, Logic",
        "source": "Titan Company Official",
        "selection_mode": "interview_assessment",
        "job_category": "conglomerate",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "CAD, Precision Machining, IoT Wearables, Quality Assurance",
        "ctc_lpa": 7.5,
        "days_ago": 11,
        "days_ahead": 29
    },
    {
        "title": "JSW Steel Graduate Engineer Trainee (Core Steel, Metallurgy & Automation) 2026 (750 Posts)",
        "title_gu": "જેએસડબ્લ્યુ સ્ટીલ (JSW Steel) ગ્રેજ્યુએટ એન્જિનિયર ટ્રેઇની ૨૦૨૬ (૭૫૦ જગ્યાઓ)",
        "organization": "JSW Steel Limited",
        "department": "Integrated Steel Plant Operations, Rolling Mills & Automation",
        "gov_level": "Private",
        "state": "All India",
        "district": "Vijayanagar",
        "board_category": "Corporate",
        "vacancies": 750,
        "qualification": "B.E. / B.Tech in Metallurgy / Mechanical / Electrical / Chemical / CSE with min 60%",
        "qualification_level": "Engineering",
        "age_min": 21,
        "age_max": 27,
        "salary_text": "CTC ₹6.0 LPA to ₹8.0 LPA + Accommodation",
        "notification_number": "JSW/GET-STEEL/2026",
        "apply_url": "https://www.jsw.in/careers",
        "official_website": "https://www.jsw.in",
        "selection_process": "Online Technical Test -> Technical Interview -> Medical",
        "syllabus_summary": "Metallurgical Processes, Strength of Materials, Industrial Automation",
        "source": "JSW Official",
        "selection_mode": "written_exam",
        "job_category": "conglomerate",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "DCS/SCADA, Industrial Automation, Metallurgy, Six Sigma",
        "ctc_lpa": 8.0,
        "days_ago": 13,
        "days_ahead": 27
    },
    {
        "title": "Vedanta Limited Graduate Engineer Trainee (Cairn Oil & Gas / Sterlite) 2026 (650 Posts)",
        "title_gu": "વેદાંતા લિમિટેડ (Vedanta) ગ્રેજ્યુએટ એન્જિનિયર ટ્રેઇની ૨૦૨૬ (૬૫૦ જગ્યાઓ)",
        "organization": "Vedanta Limited",
        "department": "Cairn Oil & Gas Exploration, Zinc & Aluminium Smelting",
        "gov_level": "Private",
        "state": "All India",
        "district": "All India",
        "board_category": "Corporate",
        "vacancies": 650,
        "qualification": "B.E. / B.Tech in Petroleum / Chemical / Mechanical / Electrical / Mining with min 60%",
        "qualification_level": "Engineering",
        "age_min": 21,
        "age_max": 27,
        "salary_text": "CTC ₹6.5 LPA to ₹8.5 LPA + Offshore / Site Allowances",
        "notification_number": "VEDANTA/GET/2026",
        "apply_url": "https://www.vedantalimited.com/careers",
        "official_website": "https://www.vedantalimited.com",
        "selection_process": "Aptitude & Technical Exam -> Group Discussion -> Panel Interview",
        "syllabus_summary": "Thermodynamics, Exploration Engineering, Industrial Safety, Fluid Mechanics",
        "source": "Vedanta Careers Official",
        "selection_mode": "written_exam",
        "job_category": "conglomerate",
        "is_btech_cse": 0,
        "experience_level": "fresher",
        "tech_stack": "Petroleum Drilling, Mining Automation, SCADA, Heavy Machinery",
        "ctc_lpa": 8.5,
        "days_ago": 10,
        "days_ahead": 30
    },
    {
        "title": "Hindalco Industries Plant Operations & Metallurgy Engineer (Dahej Gujarat) 2026 (450 Posts)",
        "title_gu": "હિન્દાલ્કો ઇન્ડસ્ટ્રીઝ (દહેજ ગુજરાત) પ્લાન્ટ એન્જિનિયર ૨૦૨૬ (૪૫૦ જગ્યાઓ)",
        "organization": "Hindalco Industries Limited (Aditya Birla Group)",
        "department": "Dahej Copper Smelter, Aluminium Rolling & Sustainable Metals",
        "gov_level": "Private",
        "state": "Gujarat",
        "district": "ભરૂચ",
        "board_category": "Corporate",
        "vacancies": 450,
        "qualification": "B.E. / B.Tech in Metallurgy / Chemical / Mechanical / Electrical with min 60%",
        "qualification_level": "Engineering",
        "age_min": 21,
        "age_max": 28,
        "salary_text": "CTC ₹5.5 LPA to ₹7.5 LPA + Dahej Township Stay",
        "notification_number": "HINDALCO/DAHEJ/2026",
        "apply_url": "https://www.hindalco.com/careers",
        "official_website": "https://www.hindalco.com",
        "selection_process": "Written Aptitude Test -> Technical Interview",
        "syllabus_summary": "Extractive Metallurgy, Smelting Technology, Industrial Safety, Process Control",
        "source": "Hindalco Official",
        "selection_mode": "written_exam",
        "job_category": "conglomerate",
        "is_btech_cse": 0,
        "experience_level": "fresher",
        "tech_stack": "Smelter Control, DCS, Metallurgical Testing, Industrial Safety",
        "ctc_lpa": 7.5,
        "days_ago": 12,
        "days_ahead": 28
    },
    {
        "title": "Grasim Industries Chemical Process & Plant Engineer (Vilayat Bharuch) 2026 (350 Posts)",
        "title_gu": "ગ્રાસિમ ઇન્ડસ્ટ્રીઝ (વિલાયત ભરૂચ) કેમિકલ પ્રોસેસ એન્જિનિયર ૨૦૨૬ (૩૫૦ જગ્યાઓ)",
        "organization": "Grasim Industries Limited (Aditya Birla Group)",
        "department": "Viscose Staple Fiber (VSF), Epoxy Resins & Chemicals Plant",
        "gov_level": "Private",
        "state": "Gujarat",
        "district": "ભરૂચ",
        "board_category": "Corporate",
        "vacancies": 350,
        "qualification": "B.E. / B.Tech in Chemical / Mechanical / Instrumentation or M.Sc Chemistry",
        "qualification_level": "Engineering",
        "age_min": 21,
        "age_max": 28,
        "salary_text": "CTC ₹5.5 LPA to ₹7.2 LPA",
        "notification_number": "GRASIM/VILAYAT/2026",
        "apply_url": "https://www.grasim.com/careers",
        "official_website": "https://www.grasim.com",
        "selection_process": "Technical Written Test -> Technical Interview",
        "syllabus_summary": "Polymerization, Chemical Reactors, Process Optimization, Safety",
        "source": "Grasim Official",
        "selection_mode": "written_exam",
        "job_category": "conglomerate",
        "is_btech_cse": 0,
        "experience_level": "fresher",
        "tech_stack": "Chemical Process DCS, PLC, SAP, Industrial Hygiene",
        "ctc_lpa": 7.2,
        "days_ago": 9,
        "days_ahead": 31
    },

    # --- Additional Automobile & EV ---
    {
        "title": "Hyundai Motor India Graduate Engineer Trainee (Production & R&D) 2026 (600 Posts)",
        "title_gu": "હ્યુન્ડાઇ મોટર ઇન્ડિયા (Hyundai) ગ્રેજ્યુએટ એન્જિનિયર ટ્રેઇની ૨૦૨૬ (૬૦૦ જગ્યાઓ)",
        "organization": "Hyundai Motor India Limited",
        "department": "Vehicle Assembly, Engine Automation & Telematics R&D",
        "gov_level": "Private",
        "state": "All India",
        "district": "Sriperumbudur",
        "board_category": "Corporate",
        "vacancies": 600,
        "qualification": "B.E. / B.Tech in Mechanical / Automobile / Production / Electrical with min 65%",
        "qualification_level": "Engineering",
        "age_min": 21,
        "age_max": 27,
        "salary_text": "CTC ₹6.0 LPA to ₹8.0 LPA",
        "notification_number": "HYUNDAI/GET-RND/2026",
        "apply_url": "https://www.hyundai.com/in/en/hyundai-story/careers",
        "official_website": "https://www.hyundai.com",
        "selection_process": "Online Technical Test -> Technical Interview -> HR",
        "syllabus_summary": "Automotive Dynamics, Robotics, Mechatronics, Quality Systems",
        "source": "Hyundai Careers Official",
        "selection_mode": "written_exam",
        "job_category": "auto_ev",
        "is_btech_cse": 0,
        "experience_level": "fresher",
        "tech_stack": "Robotics SCADA, CATIA, Quality Engineering, Automotive Protocols",
        "ctc_lpa": 8.0,
        "days_ago": 14,
        "days_ahead": 26
    },
    {
        "title": "Hero MotoCorp Graduate Trainee (Two-Wheeler Product Design & R&D) 2026 (400 Posts)",
        "title_gu": "હીરો મોટોકોર્પ (Hero MotoCorp) ગ્રેજ્યુએટ ટ્રેઇની ૨૦૨૬ (૪૦૦ જગ્યાઓ)",
        "organization": "Hero MotoCorp Limited",
        "department": "Centre of Innovation & Technology (CIT), EV Vida & Two-Wheeler Design",
        "gov_level": "Private",
        "state": "All India",
        "district": "Gurugram",
        "board_category": "Corporate",
        "vacancies": 400,
        "qualification": "B.E. / B.Tech in Mechanical / Automobile / Electrical / Production with min 60%",
        "qualification_level": "Engineering",
        "age_min": 21,
        "age_max": 27,
        "salary_text": "CTC ₹5.5 LPA to ₹7.5 LPA",
        "notification_number": "HERO/CIT-GET/2026",
        "apply_url": "https://jobs.heromotocorp.com",
        "official_website": "https://www.heromotocorp.com",
        "selection_process": "Online Cognitive Exam -> Technical Interview -> HR",
        "syllabus_summary": "Internal Combustion, EV Powertrains, Chassis Dynamics, Manufacturing",
        "source": "Hero MotoCorp Official",
        "selection_mode": "written_exam",
        "job_category": "auto_ev",
        "is_btech_cse": 0,
        "experience_level": "fresher",
        "tech_stack": "CATIA, SolidWorks, EV Powertrain, CAE Simulation",
        "ctc_lpa": 7.5,
        "days_ago": 12,
        "days_ahead": 28
    },
    {
        "title": "Bajaj Auto Graduate Engineer Trainee (Manufacturing & R&D) 2026 (500 Posts)",
        "title_gu": "બજાજ ઓટો (Bajaj Auto) ગ્રેજ્યુએટ એન્જિનિયર ટ્રેઇની ૨૦૨૬ (૫૦૦ જગ્યાઓ)",
        "organization": "Bajaj Auto Limited",
        "department": "Chakan Plant, Pulsar R&D & Chetak Electric Vehicle Facility",
        "gov_level": "Private",
        "state": "All India",
        "district": "Pune",
        "board_category": "Corporate",
        "vacancies": 500,
        "qualification": "B.E. / B.Tech in Mechanical / Automobile / Electrical / Production with min 65%",
        "qualification_level": "Engineering",
        "age_min": 21,
        "age_max": 27,
        "salary_text": "CTC ₹6.0 LPA to ₹8.0 LPA",
        "notification_number": "BAJAJ-AUTO/GET/2026",
        "apply_url": "https://www.bajajauto.com/careers",
        "official_website": "https://www.bajajauto.com",
        "selection_process": "Aptitude & Technical Exam -> Group Task -> Personal Interview",
        "syllabus_summary": "Two-Wheeler Dynamics, Automotive Electronics, Manufacturing Tech",
        "source": "Bajaj Auto Official",
        "selection_mode": "written_exam",
        "job_category": "auto_ev",
        "is_btech_cse": 0,
        "experience_level": "fresher",
        "tech_stack": "Automotive Engineering, TPM, Lean Manufacturing, CAD/CAM",
        "ctc_lpa": 8.0,
        "days_ago": 10,
        "days_ahead": 30
    },
    {
        "title": "TVS Motor Company Graduate Engineering Trainee (Electric & ICE Mobility) 2026 (450 Posts)",
        "title_gu": "ટીવીએસ મોટર (TVS Motor) ગ્રેજ્યુએટ એન્જિનિયરિંગ ટ્રેઇની ૨૦૨૬ (૪૫૦ જગ્યાઓ)",
        "organization": "TVS Motor Company Limited",
        "department": "Hosur Manufacturing, TVS iQube EV Engineering & Racing Tech",
        "gov_level": "Private",
        "state": "All India",
        "district": "Hosur",
        "board_category": "Corporate",
        "vacancies": 450,
        "qualification": "B.E. / B.Tech in Mechanical / Automobile / Electrical / CSE with min 60%",
        "qualification_level": "Engineering",
        "age_min": 21,
        "age_max": 27,
        "salary_text": "CTC ₹5.8 LPA to ₹7.8 LPA",
        "notification_number": "TVS/GET-MOBILITY/26",
        "apply_url": "https://www.tvsmotor.com/careers",
        "official_website": "https://www.tvsmotor.com",
        "selection_process": "Online Technical Test -> Technical Interview -> HR",
        "syllabus_summary": "Powertrain Design, Telematics, Vehicle Dynamics, Industrial Safety",
        "source": "TVS Motor Official",
        "selection_mode": "written_exam",
        "job_category": "auto_ev",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Automotive Electronics, Embedded Systems, CAD, Quality Systems",
        "ctc_lpa": 7.8,
        "days_ago": 8,
        "days_ahead": 32
    },

    # --- Additional Pharma & Healthcare ---
    {
        "title": "Dr. Reddy's Laboratories Technical Trainee (Biologics & Active Ingredients) 2026 (700 Posts)",
        "title_gu": "ડો. રેડ્ડીઝ લેબોરેટરીઝ (Dr. Reddy's) ટેકનિકલ ટ્રેઇની ૨૦૨૬ (૭૦૦ જગ્યાઓ)",
        "organization": "Dr. Reddy's Laboratories Limited",
        "department": "Biologics Manufacturing, Small Molecules & Global QC",
        "gov_level": "Private",
        "state": "All India",
        "district": "Hyderabad",
        "board_category": "Corporate",
        "vacancies": 700,
        "qualification": "B.Pharm / M.Pharm / B.Tech (Chemical/Biotech) / M.Sc Chemistry with min 60%",
        "qualification_level": "Graduate",
        "age_min": 21,
        "age_max": 28,
        "salary_text": "CTC ₹5.0 LPA to ₹7.0 LPA",
        "notification_number": "DRREDDY/TECH-TR/2026",
        "apply_url": "https://careers.drreddys.com",
        "official_website": "https://www.drreddys.com",
        "selection_process": "Online Technical Exam -> Interview Rounds",
        "syllabus_summary": "Analytical Chemistry, Chromatography, Bio-Process Operations",
        "source": "Dr. Reddy's Official",
        "selection_mode": "written_exam",
        "job_category": "pharma",
        "is_btech_cse": 0,
        "experience_level": "fresher",
        "tech_stack": "Bioreactors, HPLC, Fermentation, cGMP Compliance",
        "ctc_lpa": 7.0,
        "days_ago": 13,
        "days_ahead": 27
    },
    {
        "title": "Cipla Limited Junior Officer & Trainee (Manufacturing & Analytical Dev) 2026 (600 Posts)",
        "title_gu": "સિપ્લા લિમિટેડ (Cipla) જુનિયર ઓફિસર અને ટ્રેઇની ૨૦૨૬ (૬૦૦ જગ્યાઓ)",
        "organization": "Cipla Limited",
        "department": "Respiratory Inhalers, Oral Solid Formulations & Sterile Manufacturing",
        "gov_level": "Private",
        "state": "Gujarat",
        "district": "અમદાવાદ",
        "board_category": "Corporate",
        "vacancies": 600,
        "qualification": "B.Pharm / M.Pharm / B.Sc / M.Sc Chemistry with min 55%",
        "qualification_level": "Graduate",
        "age_min": 21,
        "age_max": 28,
        "salary_text": "CTC ₹4.2 LPA to ₹5.8 LPA",
        "notification_number": "CIPLA/MFG-TR/2026",
        "apply_url": "https://www.cipla.com/careers",
        "official_website": "https://www.cipla.com",
        "selection_process": "Walk-In Interview / Technical Test -> HR Round",
        "syllabus_summary": "Pharmaceutical Unit Operations, Quality Assurance, Documentation",
        "source": "Cipla Official",
        "selection_mode": "walk_in",
        "job_category": "pharma",
        "is_btech_cse": 0,
        "experience_level": "fresher",
        "tech_stack": "GMP Cleanrooms, HPLC, Lyophilization, Sterile Processing",
        "ctc_lpa": 5.8,
        "days_ago": 11,
        "days_ahead": 29
    },
    {
        "title": "Lupin Limited Production Trainee & Formulation Chemist (Ankleshwar Plant) 2026 (450 Posts)",
        "title_gu": "લ્યુપિન લિમિટેડ (અંકલેશ્વર પ્લાન્ટ) પ્રોડક્શન ટ્રેઇની ૨૦૨૬ (૪૫૦ જગ્યાઓ)",
        "organization": "Lupin Limited",
        "department": "Ankleshwar API Facility, Formulation R&D & Regulatory Compliance",
        "gov_level": "Private",
        "state": "Gujarat",
        "district": "ભરૂચ",
        "board_category": "Corporate",
        "vacancies": 450,
        "qualification": "B.Sc Chemistry / B.Pharm / B.Tech Chemical Engineering with min 55%",
        "qualification_level": "Graduate",
        "age_min": 21,
        "age_max": 29,
        "salary_text": "CTC ₹4.0 LPA to ₹5.5 LPA",
        "notification_number": "LUPIN/ANKL/2026",
        "apply_url": "https://www.lupin.com/careers",
        "official_website": "https://www.lupin.com",
        "selection_process": "Technical Written Test -> Plant Technical Interview",
        "syllabus_summary": "Synthetic Chemistry, Batch Reactions, Industrial Hygiene, USFDA Norms",
        "source": "Lupin Official",
        "selection_mode": "written_exam",
        "job_category": "pharma",
        "is_btech_cse": 0,
        "experience_level": "fresher",
        "tech_stack": "Chemical Synthesis, Autoclaves, Chromatography, EHS Standards",
        "ctc_lpa": 5.5,
        "days_ago": 12,
        "days_ahead": 28
    },
    {
        "title": "Intas Pharmaceuticals Research Scientist Trainee & Regulatory Associate 2026 (400 Posts)",
        "title_gu": "ઇન્ટાસ ફાર્માસ્યુટિકલ્સ (અમદાવાદ) રિસર્ચ સાયન્ટિસ્ટ ટ્રેઇની ૨૦૨૬ (૪૦૦ જગ્યાઓ)",
        "organization": "Intas Pharmaceuticals Limited",
        "department": "Matoda/SEZ Formulations, Biopharmaceuticals & Clinical Research",
        "gov_level": "Private",
        "state": "Gujarat",
        "district": "અમદાવાદ",
        "board_category": "Corporate",
        "vacancies": 400,
        "qualification": "B.Pharm / M.Pharm / M.Sc / B.Tech Biotechnology with min 60%",
        "qualification_level": "Graduate",
        "age_min": 21,
        "age_max": 28,
        "salary_text": "CTC ₹4.5 LPA to ₹6.5 LPA",
        "notification_number": "INTAS/MATODA/2026",
        "apply_url": "https://www.intaspharma.com/careers",
        "official_website": "https://www.intaspharma.com",
        "selection_process": "Written Aptitude Test -> Technical Walk-In Interview",
        "syllabus_summary": "Bio-formulation, Bio-analytics, Method Validation, Regulatory Documentation",
        "source": "Intas Pharma Official",
        "selection_mode": "walk_in",
        "job_category": "pharma",
        "is_btech_cse": 0,
        "experience_level": "fresher",
        "tech_stack": "Chromatography, Cell Culture, Protein Purification, Electronic LIMS",
        "ctc_lpa": 6.5,
        "days_ago": 10,
        "days_ahead": 30
    },
    {
        "title": "Alembic Pharmaceuticals Graduate Trainee (Regulatory & QC - Vadodara) 2026 (350 Posts)",
        "title_gu": "એલેમ્બિક ફાર્માસ્યુટિકલ્સ (વડોદરા) ગ્રેજ્યુએટ ટ્રેઇની ૨૦૨૬ (૩૫૦ જગ્યાઓ)",
        "organization": "Alembic Pharmaceuticals Limited",
        "department": "Panelav/Karkhadi Plants, Oral Solids & Analytical Research",
        "gov_level": "Private",
        "state": "Gujarat",
        "district": "વડોદરા",
        "board_category": "Corporate",
        "vacancies": 350,
        "qualification": "B.Pharm / M.Sc Chemistry / B.Sc with min 55%",
        "qualification_level": "Graduate",
        "age_min": 21,
        "age_max": 28,
        "salary_text": "CTC ₹3.8 LPA to ₹5.2 LPA",
        "notification_number": "ALEMBIC/VAD/2026",
        "apply_url": "https://www.alembicpharmaceuticals.com/careers",
        "official_website": "https://www.alembicpharmaceuticals.com",
        "selection_process": "Technical Interview -> HR Round",
        "syllabus_summary": "Analytical Chemistry, Good Manufacturing Practices, Spectrometry",
        "source": "Alembic Official",
        "selection_mode": "interview_assessment",
        "job_category": "pharma",
        "is_btech_cse": 0,
        "experience_level": "fresher",
        "tech_stack": "HPLC, Spectrophotometer, Dissolution Testing, Documentation",
        "ctc_lpa": 5.2,
        "days_ago": 9,
        "days_ahead": 31
    },
    {
        "title": "Mankind Pharma Sales Trainee & Production Executive 2026 (600 Posts)",
        "title_gu": "મેનકાઇન્ડ ફાર્મા (Mankind Pharma) સેલ્સ ટ્રેઇની & પ્રોડક્શન ૨૦૨૬ (૬૦૦ જગ્યાઓ)",
        "organization": "Mankind Pharma Limited",
        "department": "Consumer Healthcare (Manforce, PregaNews) & Formulations",
        "gov_level": "Private",
        "state": "All India",
        "district": "Delhi",
        "board_category": "Corporate",
        "vacancies": 600,
        "qualification": "Any Graduate (B.Sc, B.Pharm, B.Com, B.Tech) with good communication",
        "qualification_level": "Graduate",
        "age_min": 21,
        "age_max": 29,
        "salary_text": "CTC ₹3.8 LPA to ₹5.0 LPA + Daily Field Allowances",
        "notification_number": "MANKIND/SALES-EXEC/2026",
        "apply_url": "https://www.mankindpharma.com/careers",
        "official_website": "https://www.mankindpharma.com",
        "selection_process": "Personal Interview -> Field Evaluation",
        "syllabus_summary": "Pharmaceutical Marketing, Pharmacology Basics, Communication Skills",
        "source": "Mankind Pharma Official",
        "selection_mode": "interview_assessment",
        "job_category": "pharma",
        "is_btech_cse": 1,
        "experience_level": "all",
        "tech_stack": "Pharma CRM, Territory Management, Digital Reporting",
        "ctc_lpa": 5.0,
        "days_ago": 14,
        "days_ahead": 26
    },

    # --- Additional FMCG & Consumer Goods ---
    {
        "title": "Britannia Industries Graduate Trainee (Food Technology & Plant Operations) 2026 (300 Posts)",
        "title_gu": "બ્રિટાનિયા ઇન્ડસ્ટ્રીઝ (ઝગડિયા પ્લાન્ટ) ગ્રેજ્યુએટ ટ્રેઇની ૨૦૨૬ (૩૦૦ જગ્યાઓ)",
        "organization": "Britannia Industries Limited",
        "department": "Jhagadia Gujarat Mega Plant, Biscuit Baking Automation & Quality Labs",
        "gov_level": "Private",
        "state": "Gujarat",
        "district": "ભરૂચ",
        "board_category": "Corporate",
        "vacancies": 300,
        "qualification": "B.Tech Food Tech / Mechanical / Electrical / Chemical or Any Graduate",
        "qualification_level": "Engineering",
        "age_min": 21,
        "age_max": 27,
        "salary_text": "CTC ₹5.5 LPA to ₹7.5 LPA",
        "notification_number": "BRITANNIA/JHAG/2026",
        "apply_url": "https://www.britannia.co.in/careers",
        "official_website": "https://www.britannia.co.in",
        "selection_process": "Online Aptitude & Technical Test -> Personal Interview",
        "syllabus_summary": "Food Safety, Industrial Ovens, Packaging Automation, Quality Audits",
        "source": "Britannia Official",
        "selection_mode": "written_exam",
        "job_category": "fmcg",
        "is_btech_cse": 0,
        "experience_level": "fresher",
        "tech_stack": "Automated Baking Lines, PLC, Food HACCP, SAP Production",
        "ctc_lpa": 7.5,
        "days_ago": 10,
        "days_ahead": 30
    },
    {
        "title": "Marico Limited Young Leaders Trainee (Consumer Brands & Sales) 2026 (200 Posts)",
        "title_gu": "મેરિકો (Marico - Parachute & Saffola) યંગ લીડર્સ ટ્રેઇની ૨૦૨૬ (૨૦૦ જગ્યાઓ)",
        "organization": "Marico Limited",
        "department": "Consumer Goods (Parachute, Saffola, Livon), Supply Chain & Digital Sales",
        "gov_level": "Private",
        "state": "All India",
        "district": "Mumbai",
        "board_category": "Corporate",
        "vacancies": 200,
        "qualification": "Graduate in any stream (B.Tech, B.Com, BBA, B.Sc) with min 60%",
        "qualification_level": "Graduate",
        "age_min": 21,
        "age_max": 28,
        "salary_text": "CTC ₹6.0 LPA to ₹9.0 LPA",
        "notification_number": "MARICO/YLP/2026",
        "apply_url": "https://marico.com/india/careers",
        "official_website": "https://marico.com",
        "selection_process": "Digital Assessment -> Discovery Workshop -> Leadership Interview",
        "syllabus_summary": "Consumer Marketing, Brand Analytics, Supply Logistics, Leadership",
        "source": "Marico Official",
        "selection_mode": "interview_assessment",
        "job_category": "fmcg",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "FMCG Analytics, Supply Chain Optimization, Advanced Excel",
        "ctc_lpa": 9.0,
        "days_ago": 8,
        "days_ahead": 32
    },
    {
        "title": "Dabur India Management Trainee (Ayurvedic Consumer Healthcare) 2026 (250 Posts)",
        "title_gu": "ડાબર ઇન્ડિયા (Dabur) મેનેજમેન્ટ ટ્રેઇની ૨૦૨૬ (૨૫૦ જગ્યાઓ)",
        "organization": "Dabur India Limited",
        "department": "Ayurvedic Healthcare, Personal Care & Manufacturing Operations",
        "gov_level": "Private",
        "state": "All India",
        "district": "Ghaziabad",
        "board_category": "Corporate",
        "vacancies": 250,
        "qualification": "Any Graduate (B.Tech, B.Sc, B.Com, BBA) or MBA with min 55%",
        "qualification_level": "Graduate",
        "age_min": 21,
        "age_max": 28,
        "salary_text": "CTC ₹5.5 LPA to ₹8.0 LPA",
        "notification_number": "DABUR/MT/2026",
        "apply_url": "https://www.dabur.com/careers",
        "official_website": "https://www.dabur.com",
        "selection_process": "Aptitude Assessment -> Group Discussion -> Panel Interview",
        "syllabus_summary": "Supply Chain Dynamics, Consumer Health Awareness, Business Logic",
        "source": "Dabur Official",
        "selection_mode": "interview_assessment",
        "job_category": "fmcg",
        "is_btech_cse": 1,
        "experience_level": "all",
        "tech_stack": "ERP Systems, Supply Analytics, Quality Systems",
        "ctc_lpa": 8.0,
        "days_ago": 12,
        "days_ahead": 28
    },
    {
        "title": "Pidilite Industries (Fevicol) Industrial & Polymer Chemistry Trainee (Vapi Gujarat) 2026 (320 Posts)",
        "title_gu": "પીડિલાઇટ ઇન્ડસ્ટ્રીઝ (ફેવિકોલ વાપી) પોલીમર કેમિસ્ટ્રી ટ્રેઇની ૨૦૨૬ (૩૨૦ જગ્યાઓ)",
        "organization": "Pidilite Industries Limited",
        "department": "Vapi Adhesive Manufacturing, R&D Labs & Industrial Adhesives",
        "gov_level": "Private",
        "state": "Gujarat",
        "district": "સુરત",
        "board_category": "Corporate",
        "vacancies": 320,
        "qualification": "B.E. / B.Tech in Chemical / Polymer Engineering OR B.Sc / M.Sc Chemistry",
        "qualification_level": "Engineering",
        "age_min": 21,
        "age_max": 27,
        "salary_text": "CTC ₹6.0 LPA to ₹8.5 LPA",
        "notification_number": "PIDILITE/VAPI/2026",
        "apply_url": "https://www.pidilite.com/careers",
        "official_website": "https://www.pidilite.com",
        "selection_process": "Technical Written Test -> Technical Interview -> HR",
        "syllabus_summary": "Polymer Chemistry, Emulsions, Rheology, Adhesive Formulation",
        "source": "Pidilite Official",
        "selection_mode": "written_exam",
        "job_category": "fmcg",
        "is_btech_cse": 0,
        "experience_level": "fresher",
        "tech_stack": "Polymer Testing, Rheometers, Industrial Formulation, SAP",
        "ctc_lpa": 8.5,
        "days_ago": 13,
        "days_ahead": 27
    },
    {
        "title": "Havells India Graduate Engineer Trainee (Electrical Switchgear & Consumer Durables) 2026 (380 Posts)",
        "title_gu": "હેવેલ્સ ઇન્ડિયા (Havells) ગ્રેજ્યુએટ એન્જિનિયર ટ્રેઇની ૨૦૨૬ (૩૮૦ જગ્યાઓ)",
        "organization": "Havells India Limited",
        "department": "Industrial Switchgear, Smart Fans Automation & Lloyd Air Conditioning",
        "gov_level": "Private",
        "state": "All India",
        "district": "Noida",
        "board_category": "Corporate",
        "vacancies": 380,
        "qualification": "B.E. / B.Tech in Electrical / Electronics / Mechanical with min 60%",
        "qualification_level": "Engineering",
        "age_min": 21,
        "age_max": 27,
        "salary_text": "CTC ₹5.2 LPA to ₹7.0 LPA",
        "notification_number": "HAVELLS/GET/2026",
        "apply_url": "https://www.havells.com/careers.html",
        "official_website": "https://www.havells.com",
        "selection_process": "Online Technical Exam -> Personal Interview",
        "syllabus_summary": "Circuit Breakers, Switchgear Design, Power Electronics, Manufacturing",
        "source": "Havells Official",
        "selection_mode": "written_exam",
        "job_category": "fmcg",
        "is_btech_cse": 0,
        "experience_level": "fresher",
        "tech_stack": "AutoCAD Electrical, Switchgear Testing, Lean Manufacturing, Six Sigma",
        "ctc_lpa": 7.0,
        "days_ago": 11,
        "days_ahead": 29
    },
    {
        "title": "Godrej Consumer Products Future Leaders Programme 2026 (220 Posts)",
        "title_gu": "ગોદરેજ કન્ઝ્યુમર પ્રોડક્ટ્સ ફ્યુચર લીડર્સ પ્રોગ્રામ ૨૦૨૬ (૨૨૦ જગ્યાઓ)",
        "organization": "Godrej Consumer Products Limited (GCPL)",
        "department": "Personal Care (Cinthol, Goodknight, Godrej Expert) & Smart Factory",
        "gov_level": "Private",
        "state": "All India",
        "district": "Mumbai",
        "board_category": "Corporate",
        "vacancies": 220,
        "qualification": "Graduate in any stream or B.Tech / MBA with min 60%",
        "qualification_level": "Graduate",
        "age_min": 21,
        "age_max": 28,
        "salary_text": "CTC ₹7.0 LPA to ₹10.0 LPA",
        "notification_number": "GODREJ/GCPL-FLP/2026",
        "apply_url": "https://www.godrejcp.com/careers",
        "official_website": "https://www.godrejcp.com",
        "selection_process": "Aptitude Assessment -> Business Case Round -> Leadership Interview",
        "syllabus_summary": "Market Penetration, FMCG Economics, Supply Chain Resilience",
        "source": "Godrej Official",
        "selection_mode": "interview_assessment",
        "job_category": "fmcg",
        "is_btech_cse": 1,
        "experience_level": "fresher",
        "tech_stack": "Supply Chain Analytics, FMCG Planning, ERP, Advanced Excel",
        "ctc_lpa": 10.0,
        "days_ago": 9,
        "days_ahead": 31
    },

    # --- Additional Gujarat Private Leaders ---
    {
        "title": "Cadila Pharmaceuticals Officer Trainee (Biotech, Formulations & QC) 2026 (300 Posts)",
        "title_gu": "કેડિલા ફાર્માસ્યુટિકલ્સ (ધોળકા પ્લાન્ટ) ઓફિસર ટ્રેઇની ૨૦૨૬ (૩૦૦ જગ્યાઓ)",
        "organization": "Cadila Pharmaceuticals Limited",
        "department": "Dholka Formulation Plant, Biotech Vaccines & Quality Control",
        "gov_level": "Private",
        "state": "Gujarat",
        "district": "અમદાવાદ",
        "board_category": "Corporate",
        "vacancies": 300,
        "qualification": "B.Pharm / M.Pharm / B.Sc / M.Sc or B.Tech Biotech with min 55%",
        "qualification_level": "Graduate",
        "age_min": 21,
        "age_max": 28,
        "salary_text": "CTC ₹4.0 LPA to ₹5.5 LPA",
        "notification_number": "CADILA/DHOLKA/2026",
        "apply_url": "https://www.cadilapharma.com/careers",
        "official_website": "https://www.cadilapharma.com",
        "selection_process": "Walk-In Interview -> Technical Assessment",
        "syllabus_summary": "Pharma Chemistry, Cleanroom Protocol, Quality Assurance",
        "source": "Cadila Pharma Official",
        "selection_mode": "walk_in",
        "job_category": "gujarat_champions",
        "is_btech_cse": 0,
        "experience_level": "fresher",
        "tech_stack": "HPLC, Fermentation, Cleanrooms, QC Sampling",
        "ctc_lpa": 5.5,
        "days_ago": 13,
        "days_ahead": 27
    },
    {
        "title": "Suzlon Energy Wind Turbine & Renewable Energy Field Engineer (Kutch Gujarat) 2026 (350 Posts)",
        "title_gu": "સુઝલોન એનર્જી (કચ્છ વિન્ડ ફાર્મ્સ) વિન્ડ ટર્બાઇન ફિલ્ડ એન્જિનિયર ૨૦૨૬ (૩૫૦ જગ્યાઓ)",
        "organization": "Suzlon Energy Limited",
        "department": "Kutch Wind Farm Operations, Rotor Blade SCADA & Grid Synchronization",
        "gov_level": "Private",
        "state": "Gujarat",
        "district": "કચ્છ",
        "board_category": "Corporate",
        "vacancies": 350,
        "qualification": "B.E. / B.Tech in Electrical / Mechanical / Electronics or Diploma with min 60%",
        "qualification_level": "Engineering",
        "age_min": 21,
        "age_max": 29,
        "salary_text": "CTC ₹4.8 LPA to ₹6.5 LPA + Site Risk Allowance",
        "notification_number": "SUZLON/KUTCH/2026",
        "apply_url": "https://www.suzlon.com/careers",
        "official_website": "https://www.suzlon.com",
        "selection_process": "Written Technical Exam -> Physical Fitness Test -> Interview",
        "syllabus_summary": "Wind Turbine Generators, Power Electronics, Yaw/Pitch Control, High Voltage Safety",
        "source": "Suzlon Careers Official",
        "selection_mode": "written_exam",
        "job_category": "gujarat_champions",
        "is_btech_cse": 0,
        "experience_level": "all",
        "tech_stack": "Wind SCADA, High Voltage Substation, Turbine Maintenance, PLC",
        "ctc_lpa": 6.5,
        "days_ago": 10,
        "days_ahead": 30
    },
    {
        "title": "GHCL Limited Process Engineer & Chemical Trainee (Sutrapada Veraval) 2026 (200 Posts)",
        "title_gu": "જીએચસીએલ લિમિટેડ (સૂત્રાપાડા વેરાવળ) પ્રોસેસ એન્જિનિયર ૨૦૨૬ (૨૦૦ જગ્યાઓ)",
        "organization": "GHCL Limited (Gujarat Heavy Chemicals)",
        "department": "Soda Ash Plant, Industrial Salt Extraction & Energy Cogeneration",
        "gov_level": "Private",
        "state": "Gujarat",
        "district": "સુરત",
        "board_category": "Corporate",
        "vacancies": 200,
        "qualification": "B.E. / B.Tech in Chemical / Mechanical / Electrical with min 55%",
        "qualification_level": "Engineering",
        "age_min": 21,
        "age_max": 28,
        "salary_text": "CTC ₹4.2 LPA to ₹5.8 LPA + Coastal Allowance",
        "notification_number": "GHCL/SUTRAPADA/2026",
        "apply_url": "https://www.ghcl.co.in/careers",
        "official_website": "https://www.ghcl.co.in",
        "selection_process": "Technical Aptitude Test -> Personal Interview",
        "syllabus_summary": "Solvay Soda Ash Process, Evaporation, Chemical Pumps, Boiler Dynamics",
        "source": "GHCL Official",
        "selection_mode": "written_exam",
        "job_category": "gujarat_champions",
        "is_btech_cse": 0,
        "experience_level": "fresher",
        "tech_stack": "DCS, Chemical Process Control, Boiler Operations, Industrial Safety",
        "ctc_lpa": 5.8,
        "days_ago": 12,
        "days_ahead": 28
    }
]

